//-----------------------------------------------------------------------
// <auto-generated>
// <copyright file="AddressLabel.Designer.cs" company="Microsoft Corporation and Crown copyright 2007 - 2010.">
// Copyright (c) Microsoft Corporation and Crown copyright 2007 - 2010.
// All rights reserved.
//
// CERTAIN PARTS OF THIS WORK CONTAIN SOFTWARE CODE THAT IS LICENSED 
// FOR USE UNDER THE MICROSOFT PUBLIC LICENSE. DISTRIBUTION, IN SOURCE CODE 
// OR OBJECT CODE FORM, OF THOSE PARTS MUST COMPLY WITH THE TERMS OF THE 
// PUBLIC LICENSE. SEE http://www.microsoft.com/opensource/licenses.mspx 
// FOR DETAILS.  
// IF YOU BRING A PATENT CLAIM AGAINST ANY CONTRIBUTOR OVER PATENTS THAT 
// YOU CLAIM ARE INFRINGED BY THE PUBLIC LICENSE SOFTWARE, YOUR PATENT 
// LICENSE FROM SUCH CONTRIBUTOR TO THE SOFTWARE ENDS AUTOMATICALLY.
//
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
// </copyright>
//AddressLabel Designer
 //</auto-generated>
//-----------------------------------------------------------------------

namespace NhsCui.Toolkit.WinForms
{
    /// <summary>
    /// 
    /// </summary>
    public partial class AddressLabel
    {
        
        /// <summary>
        /// flowAddressField1 mem var
        /// </summary>
        private System.Windows.Forms.Label flowAddressField1;
        
        /// <summary>
        /// flowAddressField2 mem var
        /// </summary>
        private System.Windows.Forms.Label flowAddressField2;
        
        /// <summary>
        /// flowAddressField3 mem var
        /// </summary>
        private System.Windows.Forms.Label flowAddressField3;
        
        /// <summary>
        /// flowAddressField4 mem var
        /// </summary>
        private System.Windows.Forms.Label flowAddressField4;
        
        /// <summary>
        /// flowAddressField5 mem var
        /// </summary>
        private System.Windows.Forms.Label flowAddressField5;
        
        /// <summary>
        /// flowAddressField6 mem var
        /// </summary>
        private System.Windows.Forms.Label flowAddressField6;
        
        /// <summary>
        /// flowAddressField7 mem var
        /// </summary>
        private System.Windows.Forms.Label flowAddressField7;
        
        /// <summary>
        /// tableAddressField2 mem var
        /// </summary>
        private System.Windows.Forms.Label tableAddressField2;
        
        /// <summary>
        /// tableAddressField3 mem var
        /// </summary>
        private System.Windows.Forms.Label tableAddressField3;
        
        /// <summary>
        /// tableAddressField4 mem var
        /// </summary>
        private System.Windows.Forms.Label tableAddressField4;
        
        /// <summary>
        /// tableAddressField5 mem var
        /// </summary>
        private System.Windows.Forms.Label tableAddressField5;
        
        /// <summary>
        /// tableAddressField6 mem var
        /// </summary>
        private System.Windows.Forms.Label tableAddressField6;
        
        /// <summary>
        /// tableAddressField7 mem var
        /// </summary>
        private System.Windows.Forms.Label tableAddressField7;
        
        /// <summary>
        /// tableAddressField1 mem var
        /// </summary>
        private System.Windows.Forms.Label tableAddressField1;

        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.inlineFlowLayoutPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.addresslabelTypeInlineLayout = new System.Windows.Forms.Label();
            this.flowAddressField1 = new System.Windows.Forms.Label();
            this.flowAddressField2 = new System.Windows.Forms.Label();
            this.flowAddressField3 = new System.Windows.Forms.Label();
            this.flowAddressField4 = new System.Windows.Forms.Label();
            this.flowAddressField5 = new System.Windows.Forms.Label();
            this.flowAddressField6 = new System.Windows.Forms.Label();
            this.flowAddressField7 = new System.Windows.Forms.Label();
            this.informTableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.tableAddressField5 = new System.Windows.Forms.Label();
            this.tableAddressField2 = new System.Windows.Forms.Label();
            this.tableAddressField4 = new System.Windows.Forms.Label();
            this.tableAddressField6 = new System.Windows.Forms.Label();
            this.tableAddressField7 = new System.Windows.Forms.Label();
            this.tableAddressField3 = new System.Windows.Forms.Label();
            this.tableAddressField1 = new System.Windows.Forms.Label();
            this.addressTypeLabel = new System.Windows.Forms.Label();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.inlineFlowLayoutPanel.SuspendLayout();
            this.informTableLayoutPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // inlineFlowLayoutPanel
            // 
            this.inlineFlowLayoutPanel.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.inlineFlowLayoutPanel.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.inlineFlowLayoutPanel.Controls.Add(this.addresslabelTypeInlineLayout);
            this.inlineFlowLayoutPanel.Controls.Add(this.flowAddressField1);
            this.inlineFlowLayoutPanel.Controls.Add(this.flowAddressField2);
            this.inlineFlowLayoutPanel.Controls.Add(this.flowAddressField3);
            this.inlineFlowLayoutPanel.Controls.Add(this.flowAddressField4);
            this.inlineFlowLayoutPanel.Controls.Add(this.flowAddressField5);
            this.inlineFlowLayoutPanel.Controls.Add(this.flowAddressField6);
            this.inlineFlowLayoutPanel.Controls.Add(this.flowAddressField7);
            this.inlineFlowLayoutPanel.Location = new System.Drawing.Point(0, 0);
            this.inlineFlowLayoutPanel.Name = "inlineFlowLayoutPanel";
            this.inlineFlowLayoutPanel.Size = new System.Drawing.Size(134, 123);
            this.inlineFlowLayoutPanel.TabIndex = 0;
            // 
            // addresslabelTypeInlineLayout
            // 
            this.addresslabelTypeInlineLayout.AutoSize = true;
            this.addresslabelTypeInlineLayout.Location = new System.Drawing.Point(0, 0);
            this.addresslabelTypeInlineLayout.Margin = new System.Windows.Forms.Padding(0);
            this.addresslabelTypeInlineLayout.Name = "addresslabelTypeInlineLayout";
            this.addresslabelTypeInlineLayout.Size = new System.Drawing.Size(0, 13);
            this.addresslabelTypeInlineLayout.TabIndex = 7;
            // 
            // flowAddressField1
            // 
            this.flowAddressField1.AutoSize = true;
            this.flowAddressField1.Location = new System.Drawing.Point(0, 0);
            this.flowAddressField1.Margin = new System.Windows.Forms.Padding(0);
            this.flowAddressField1.Name = "flowAddressField1";
            this.flowAddressField1.Size = new System.Drawing.Size(0, 13);
            this.flowAddressField1.TabIndex = 0;
            // 
            // flowAddressField2
            // 
            this.flowAddressField2.AutoSize = true;
            this.flowAddressField2.Location = new System.Drawing.Point(0, 0);
            this.flowAddressField2.Margin = new System.Windows.Forms.Padding(0);
            this.flowAddressField2.Name = "flowAddressField2";
            this.flowAddressField2.Size = new System.Drawing.Size(0, 13);
            this.flowAddressField2.TabIndex = 1;
            // 
            // flowAddressField3
            // 
            this.flowAddressField3.AutoSize = true;
            this.flowAddressField3.Location = new System.Drawing.Point(0, 0);
            this.flowAddressField3.Margin = new System.Windows.Forms.Padding(0);
            this.flowAddressField3.Name = "flowAddressField3";
            this.flowAddressField3.Size = new System.Drawing.Size(0, 13);
            this.flowAddressField3.TabIndex = 2;
            // 
            // flowAddressField4
            // 
            this.flowAddressField4.AutoSize = true;
            this.flowAddressField4.Location = new System.Drawing.Point(0, 0);
            this.flowAddressField4.Margin = new System.Windows.Forms.Padding(0);
            this.flowAddressField4.Name = "flowAddressField4";
            this.flowAddressField4.Size = new System.Drawing.Size(0, 13);
            this.flowAddressField4.TabIndex = 3;
            // 
            // flowAddressField5
            // 
            this.flowAddressField5.AutoSize = true;
            this.flowAddressField5.Location = new System.Drawing.Point(0, 0);
            this.flowAddressField5.Margin = new System.Windows.Forms.Padding(0);
            this.flowAddressField5.Name = "flowAddressField5";
            this.flowAddressField5.Size = new System.Drawing.Size(0, 13);
            this.flowAddressField5.TabIndex = 4;
            // 
            // flowAddressField6
            // 
            this.flowAddressField6.AutoSize = true;
            this.flowAddressField6.Location = new System.Drawing.Point(0, 0);
            this.flowAddressField6.Margin = new System.Windows.Forms.Padding(0);
            this.flowAddressField6.Name = "flowAddressField6";
            this.flowAddressField6.Size = new System.Drawing.Size(0, 13);
            this.flowAddressField6.TabIndex = 5;
            // 
            // flowAddressField7
            // 
            this.flowAddressField7.AutoSize = true;
            this.flowAddressField7.Location = new System.Drawing.Point(0, 0);
            this.flowAddressField7.Margin = new System.Windows.Forms.Padding(0);
            this.flowAddressField7.Name = "flowAddressField7";
            this.flowAddressField7.Size = new System.Drawing.Size(0, 13);
            this.flowAddressField7.TabIndex = 6;
            // 
            // informTableLayoutPanel
            // 
            this.informTableLayoutPanel.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.informTableLayoutPanel.AutoSize = true;
            this.informTableLayoutPanel.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.informTableLayoutPanel.ColumnCount = 1;
            this.informTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.informTableLayoutPanel.Controls.Add(this.tableAddressField5, 0, 5);
            this.informTableLayoutPanel.Controls.Add(this.tableAddressField2, 0, 2);
            this.informTableLayoutPanel.Controls.Add(this.tableAddressField4, 0, 4);
            this.informTableLayoutPanel.Controls.Add(this.tableAddressField6, 0, 6);
            this.informTableLayoutPanel.Controls.Add(this.tableAddressField7, 0, 7);
            this.informTableLayoutPanel.Controls.Add(this.tableAddressField3, 0, 3);
            this.informTableLayoutPanel.Controls.Add(this.tableAddressField1, 0, 1);
            this.informTableLayoutPanel.Controls.Add(this.addressTypeLabel, 0, 0);
            this.informTableLayoutPanel.Location = new System.Drawing.Point(0, 0);
            this.informTableLayoutPanel.Name = "informTableLayoutPanel";
            this.informTableLayoutPanel.RowCount = 8;
            this.informTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.informTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.informTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.informTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.informTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.informTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.informTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.informTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.informTableLayoutPanel.Size = new System.Drawing.Size(134, 104);
            this.informTableLayoutPanel.TabIndex = 14;
            this.informTableLayoutPanel.Visible = false;
            // 
            // tableAddressField5
            // 
            this.tableAddressField5.AutoSize = true;
            this.tableAddressField5.Location = new System.Drawing.Point(0, 65);
            this.tableAddressField5.Margin = new System.Windows.Forms.Padding(0);
            this.tableAddressField5.Name = "tableAddressField5";
            this.tableAddressField5.Size = new System.Drawing.Size(0, 13);
            this.tableAddressField5.TabIndex = 11;
            // 
            // tableAddressField2
            // 
            this.tableAddressField2.AutoSize = true;
            this.tableAddressField2.Location = new System.Drawing.Point(0, 26);
            this.tableAddressField2.Margin = new System.Windows.Forms.Padding(0);
            this.tableAddressField2.Name = "tableAddressField2";
            this.tableAddressField2.Size = new System.Drawing.Size(0, 13);
            this.tableAddressField2.TabIndex = 8;
            // 
            // tableAddressField4
            // 
            this.tableAddressField4.AutoSize = true;
            this.tableAddressField4.Location = new System.Drawing.Point(0, 52);
            this.tableAddressField4.Margin = new System.Windows.Forms.Padding(0);
            this.tableAddressField4.Name = "tableAddressField4";
            this.tableAddressField4.Size = new System.Drawing.Size(0, 13);
            this.tableAddressField4.TabIndex = 10;
            // 
            // tableAddressField6
            // 
            this.tableAddressField6.AutoSize = true;
            this.tableAddressField6.Location = new System.Drawing.Point(0, 78);
            this.tableAddressField6.Margin = new System.Windows.Forms.Padding(0);
            this.tableAddressField6.Name = "tableAddressField6";
            this.tableAddressField6.Size = new System.Drawing.Size(0, 13);
            this.tableAddressField6.TabIndex = 12;
            // 
            // tableAddressField7
            // 
            this.tableAddressField7.AutoSize = true;
            this.tableAddressField7.Location = new System.Drawing.Point(0, 91);
            this.tableAddressField7.Margin = new System.Windows.Forms.Padding(0);
            this.tableAddressField7.Name = "tableAddressField7";
            this.tableAddressField7.Size = new System.Drawing.Size(0, 13);
            this.tableAddressField7.TabIndex = 13;
            // 
            // tableAddressField3
            // 
            this.tableAddressField3.AutoSize = true;
            this.tableAddressField3.Location = new System.Drawing.Point(0, 39);
            this.tableAddressField3.Margin = new System.Windows.Forms.Padding(0);
            this.tableAddressField3.Name = "tableAddressField3";
            this.tableAddressField3.Size = new System.Drawing.Size(0, 13);
            this.tableAddressField3.TabIndex = 9;
            // 
            // tableAddressField1
            // 
            this.tableAddressField1.AutoSize = true;
            this.tableAddressField1.Location = new System.Drawing.Point(0, 13);
            this.tableAddressField1.Margin = new System.Windows.Forms.Padding(0);
            this.tableAddressField1.Name = "tableAddressField1";
            this.tableAddressField1.Size = new System.Drawing.Size(0, 13);
            this.tableAddressField1.TabIndex = 7;
            // 
            // addressTypeLabel
            // 
            this.addressTypeLabel.AutoSize = true;
            this.addressTypeLabel.Location = new System.Drawing.Point(0, 0);
            this.addressTypeLabel.Margin = new System.Windows.Forms.Padding(0);
            this.addressTypeLabel.Name = "addressTypeLabel";
            this.addressTypeLabel.Size = new System.Drawing.Size(0, 13);
            this.addressTypeLabel.TabIndex = 14;
            // 
            // AddressLabel
            // 
            this.AutoSize = true;
            this.Controls.Add(this.informTableLayoutPanel);
            this.Controls.Add(this.inlineFlowLayoutPanel);
            this.Name = "AddressLabel";
            this.Size = new System.Drawing.Size(134, 123);
            this.inlineFlowLayoutPanel.ResumeLayout(false);
            this.inlineFlowLayoutPanel.PerformLayout();
            this.informTableLayoutPanel.ResumeLayout(false);
            this.informTableLayoutPanel.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label addressTypeLabel;
        private System.Windows.Forms.Label addresslabelTypeInlineLayout;
        internal System.Windows.Forms.FlowLayoutPanel inlineFlowLayoutPanel;
        internal System.Windows.Forms.TableLayoutPanel informTableLayoutPanel;
        private System.Windows.Forms.ToolTip toolTip1;
    }
}
