//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhsCui.Toolkit.Web.DateInputBoxControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NhsCui.Toolkit.Web.DateInputBoxControl.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Calendar.
        /// </summary>
        internal static string CalendarButtonCloseTitle {
            get {
                return ResourceManager.GetString("CalendarButtonCloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Calendar.
        /// </summary>
        internal static string CalendarButtonTitle {
            get {
                return ResourceManager.GetString("CalendarButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Calendar.
        /// </summary>
        internal static string closeTitle {
            get {
                return ResourceManager.GetString("closeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd-MMM-yyyy.
        /// </summary>
        internal static string DefaultWaterMark {
            get {
                return ResourceManager.GetString("DefaultWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate null string specified : .
        /// </summary>
        internal static string DuplicateNullString {
            get {
                return ResourceManager.GetString("DuplicateNullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a date, e.g. August 2005 or a shortcut, e.g. +3m or click on the calendar icon to select a date.
        /// </summary>
        internal static string FirstUseTooltipText {
            get {
                return ResourceManager.GetString("FirstUseTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to enter the displayed month and year as the date..
        /// </summary>
        internal static string monthTip {
            get {
                return ResourceManager.GetString("monthTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next month.
        /// </summary>
        internal static string nextMonth {
            get {
                return ResourceManager.GetString("nextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next year.
        /// </summary>
        internal static string nextYear {
            get {
                return ResourceManager.GetString("nextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null Date Types.
        /// </summary>
        internal static string NullStringsDropdownTitle {
            get {
                return ResourceManager.GetString("NullStringsDropdownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous month.
        /// </summary>
        internal static string prevMonth {
            get {
                return ResourceManager.GetString("prevMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous year.
        /// </summary>
        internal static string prevYear {
            get {
                return ResourceManager.GetString("prevYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to enter today&apos;s date.
        /// </summary>
        internal static string todayTitle {
            get {
                return ResourceManager.GetString("todayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to enter the displayed year as the date..
        /// </summary>
        internal static string yearTip {
            get {
                return ResourceManager.GetString("yearTip", resourceCulture);
            }
        }
    }
}
