
//-----------------------------------------------------------------------
// <auto-generated>
// <copyright file="PatientBanner.Designer.cs" company="Microsoft Corporation and Crown copyright 2007 - 2010.">
// Copyright (c) Microsoft Corporation and Crown copyright 2007 - 2010.
// All rights reserved.
//
// CERTAIN PARTS OF THIS WORK CONTAIN SOFTWARE CODE THAT IS LICENSED 
// FOR USE UNDER THE MICROSOFT PUBLIC LICENSE. DISTRIBUTION, IN SOURCE CODE 
// OR OBJECT CODE FORM, OF THOSE PARTS MUST COMPLY WITH THE TERMS OF THE 
// PUBLIC LICENSE. SEE http://www.microsoft.com/opensource/licenses.mspx 
// FOR DETAILS.  
// IF YOU BRING A PATENT CLAIM AGAINST ANY CONTRIBUTOR OVER PATENTS THAT 
// YOU CLAIM ARE INFRINGED BY THE PUBLIC LICENSE SOFTWARE, YOUR PATENT 
// LICENSE FROM SUCH CONTRIBUTOR TO THE SOFTWARE ENDS AUTOMATICALLY.
//
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
// </copyright>
// <summary>PatientBanner Designer</summary>
// </auto-generated>
//-----------------------------------------------------------------------

namespace NhsCui.Toolkit.WinForms
{
    /// <summary>
    /// 
    /// </summary>
    public partial class PatientBanner
    {
        #region Member Vars

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// toggleImageList member var
        /// </summary>
        private System.Windows.Forms.ImageList toggleImageList;

        /// <summary>
        /// genderImageList member var
        /// </summary>
        private System.Windows.Forms.ImageList genderImageList;

        /// <summary>
        /// patientBannerToolTip member var
        /// </summary>
        private System.Windows.Forms.ToolTip patientBannerToolTip;

    #endregion
        
        #region Methods

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(PatientBanner));
            this.identifierLabel = new System.Windows.Forms.Label();
            this.dateOfBirthLabel = new System.Windows.Forms.Label();
            this.genderLabel = new System.Windows.Forms.Label();
            this.dateOfBirthData = new System.Windows.Forms.Label();
            this.toggleImageList = new System.Windows.Forms.ImageList(this.components);
            this.genderImageList = new System.Windows.Forms.ImageList(this.components);
            this.patientBannerToolTip = new System.Windows.Forms.ToolTip(this.components);
            this.DeceasedPatientTransparentIcon = new System.Windows.Forms.PictureBox();
            this.dateOfDeathData = new System.Windows.Forms.Label();
            this.dateOfDeathLabel = new System.Windows.Forms.Label();
            this.patientName = new System.Windows.Forms.Label();
            this.zoneOnePanel = new System.Windows.Forms.Panel();
            this.patientDataPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.genderData = new NhsCui.Toolkit.WinForms.GenderLabel();
            this.btnGenderData = new System.Windows.Forms.LinkLabel();
            this.identifierData = new NhsCui.Toolkit.WinForms.IdentifierLabel();
            this.btnIdentifierLabel = new System.Windows.Forms.LinkLabel();
            this.ageAtDeathLabel = new System.Windows.Forms.Label();
            this.ageAtDeath = new System.Windows.Forms.Label();
            this.preferredName = new System.Windows.Forms.Label();
            this.preferredNameLabel = new System.Windows.Forms.Label();
            this.patientPicture = new System.Windows.Forms.PictureBox();
            this.zoneTwoPanel = new System.Windows.Forms.Panel();
            this.subsectionFive = new System.Windows.Forms.Panel();
            this.viewAllergyRecordLink = new System.Windows.Forms.LinkLabel();
            this.viewAllContactDetailsLink = new System.Windows.Forms.LinkLabel();
            this.viewAllAddressesLink = new System.Windows.Forms.LinkLabel();
            this.subsectionFour = new System.Windows.Forms.Panel();
            this.subsectionThree = new System.Windows.Forms.Panel();
            this.addressField = new NhsCui.Toolkit.WinForms.AddressLabel();
            this.phoneEmailData = new NhsCui.Toolkit.WinForms.ContactLabel();
            this.zoneOneHeaderStripPanel = new System.Windows.Forms.Panel();
            this.contactDetailsPreviewLabel = new System.Windows.Forms.Label();
            this.allergyIcon = new System.Windows.Forms.Button();
            this.allergiesInformationLabel = new System.Windows.Forms.Label();
            this.subsectionFourTitle = new System.Windows.Forms.Label();
            this.subsectionThreeTitle = new System.Windows.Forms.Label();
            this.toggleDropButton = new System.Windows.Forms.Button();
            this.subsectionTwoTitleLabel = new System.Windows.Forms.Label();
            this.subsectionOneTitleLabel = new System.Windows.Forms.Label();
            this.addressPreviewLabel = new System.Windows.Forms.Label();
            this.borderPanel = new System.Windows.Forms.Panel();
            this.allergyIconsImageList = new System.Windows.Forms.ImageList(this.components);
            this.subsectionOneBorder = new System.Windows.Forms.Panel();
            this.subsectionTwoBorder = new System.Windows.Forms.Panel();
            this.subsectionThreeBorder = new System.Windows.Forms.Panel();
            this.subsectionFourBorder = new System.Windows.Forms.Panel();
            this.expandCollpaseImageBorder = new System.Windows.Forms.Panel();
            ((System.ComponentModel.ISupportInitialize)(this.DeceasedPatientTransparentIcon)).BeginInit();
            this.zoneOnePanel.SuspendLayout();
            this.patientDataPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.identifierData)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.patientPicture)).BeginInit();
            this.zoneTwoPanel.SuspendLayout();
            this.zoneOneHeaderStripPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // identifierLabel
            // 
            this.identifierLabel.AutoEllipsis = true;
            this.identifierLabel.AutoSize = true;
            this.identifierLabel.BackColor = System.Drawing.Color.Transparent;
            this.identifierLabel.ForeColor = System.Drawing.SystemColors.ControlText;
            this.identifierLabel.Location = new System.Drawing.Point(220, 0);
            this.identifierLabel.Margin = new System.Windows.Forms.Padding(0);
            this.identifierLabel.Name = "identifierLabel";
            this.identifierLabel.Padding = new System.Windows.Forms.Padding(1);
            this.identifierLabel.Size = new System.Drawing.Size(32, 15);
            this.identifierLabel.TabIndex = 5;
            this.identifierLabel.Text = "NHS";
            this.identifierLabel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.identifierLabel.MouseLeave += new System.EventHandler(this.IdentifierLabel_MouseLeave);
            this.identifierLabel.MouseEnter += new System.EventHandler(this.IdentifierLabel_MouseEnter);
            // 
            // dateOfBirthLabel
            // 
            this.dateOfBirthLabel.AutoEllipsis = true;
            this.dateOfBirthLabel.AutoSize = true;
            this.dateOfBirthLabel.BackColor = System.Drawing.Color.Transparent;
            this.dateOfBirthLabel.ForeColor = System.Drawing.SystemColors.ControlText;
            this.dateOfBirthLabel.Location = new System.Drawing.Point(0, 0);
            this.dateOfBirthLabel.Margin = new System.Windows.Forms.Padding(0);
            this.dateOfBirthLabel.Name = "dateOfBirthLabel";
            this.dateOfBirthLabel.Padding = new System.Windows.Forms.Padding(1);
            this.dateOfBirthLabel.Size = new System.Drawing.Size(31, 15);
            this.dateOfBirthLabel.TabIndex = 10;
            this.dateOfBirthLabel.Text = "Born";
            this.dateOfBirthLabel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // genderLabel
            // 
            this.genderLabel.AutoEllipsis = true;
            this.genderLabel.AutoSize = true;
            this.genderLabel.BackColor = System.Drawing.Color.Transparent;
            this.genderLabel.ForeColor = System.Drawing.SystemColors.ControlText;
            this.genderLabel.Location = new System.Drawing.Point(33, 0);
            this.genderLabel.Margin = new System.Windows.Forms.Padding(0);
            this.genderLabel.Name = "genderLabel";
            this.genderLabel.Padding = new System.Windows.Forms.Padding(1);
            this.genderLabel.Size = new System.Drawing.Size(44, 15);
            this.genderLabel.TabIndex = 0;
            this.genderLabel.Text = "Gender";
            this.genderLabel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.genderLabel.MouseLeave += new System.EventHandler(this.GenderLabel_MouseLeave);
            this.genderLabel.MouseEnter += new System.EventHandler(this.GenderLabel_MouseEnter);
            // 
            // dateOfBirthData
            // 
            this.dateOfBirthData.AutoEllipsis = true;
            this.dateOfBirthData.AutoSize = true;
            this.dateOfBirthData.BackColor = System.Drawing.Color.Transparent;
            this.dateOfBirthData.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dateOfBirthData.ForeColor = System.Drawing.SystemColors.ControlText;
            this.dateOfBirthData.Location = new System.Drawing.Point(31, 0);
            this.dateOfBirthData.Margin = new System.Windows.Forms.Padding(0);
            this.dateOfBirthData.Name = "dateOfBirthData";
            this.dateOfBirthData.Padding = new System.Windows.Forms.Padding(1);
            this.dateOfBirthData.Size = new System.Drawing.Size(2, 15);
            this.dateOfBirthData.TabIndex = 20;
            this.dateOfBirthData.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // toggleImageList
            // 
            this.toggleImageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("toggleImageList.ImageStream")));
            this.toggleImageList.TransparentColor = System.Drawing.Color.White;
            this.toggleImageList.Images.SetKeyName(0, "");
            this.toggleImageList.Images.SetKeyName(1, "");
            // 
            // genderImageList
            // 
            this.genderImageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("genderImageList.ImageStream")));
            this.genderImageList.TransparentColor = System.Drawing.Color.Transparent;
            this.genderImageList.Images.SetKeyName(0, "generic-female.png");
            this.genderImageList.Images.SetKeyName(1, "generic-male.png");
            this.genderImageList.Images.SetKeyName(2, "NotSpecified.png");
            // 
            // DeceasedPatientTransparentIcon
            // 
            this.DeceasedPatientTransparentIcon.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.DeceasedPatientTransparentIcon.Image = global::NhsCui.Toolkit.WinForms.Properties.Resources.DeceasedPatientTransparentIcon;
            this.DeceasedPatientTransparentIcon.Location = new System.Drawing.Point(55, 20);
            this.DeceasedPatientTransparentIcon.Name = "DeceasedPatientTransparentIcon";
            this.DeceasedPatientTransparentIcon.Size = new System.Drawing.Size(1, 1);
            this.DeceasedPatientTransparentIcon.TabIndex = 26;
            this.DeceasedPatientTransparentIcon.TabStop = false;
            this.patientBannerToolTip.SetToolTip(this.DeceasedPatientTransparentIcon, "This patient is deceased");
            // 
            // dateOfDeathData
            // 
            this.dateOfDeathData.AutoSize = true;
            this.dateOfDeathData.BackColor = System.Drawing.Color.Transparent;
            this.dateOfDeathData.ForeColor = System.Drawing.SystemColors.ControlText;
            this.dateOfDeathData.Location = new System.Drawing.Point(31, 15);
            this.dateOfDeathData.Margin = new System.Windows.Forms.Padding(0);
            this.dateOfDeathData.Name = "dateOfDeathData";
            this.dateOfDeathData.Padding = new System.Windows.Forms.Padding(1);
            this.dateOfDeathData.Size = new System.Drawing.Size(2, 15);
            this.dateOfDeathData.TabIndex = 22;
            this.dateOfDeathData.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // dateOfDeathLabel
            // 
            this.dateOfDeathLabel.AutoEllipsis = true;
            this.dateOfDeathLabel.AutoSize = true;
            this.dateOfDeathLabel.BackColor = System.Drawing.Color.Transparent;
            this.dateOfDeathLabel.ForeColor = System.Drawing.SystemColors.ControlText;
            this.dateOfDeathLabel.Location = new System.Drawing.Point(0, 15);
            this.dateOfDeathLabel.Margin = new System.Windows.Forms.Padding(0);
            this.dateOfDeathLabel.Name = "dateOfDeathLabel";
            this.dateOfDeathLabel.Padding = new System.Windows.Forms.Padding(1);
            this.dateOfDeathLabel.Size = new System.Drawing.Size(31, 15);
            this.dateOfDeathLabel.TabIndex = 21;
            this.dateOfDeathLabel.Text = "Died";
            this.dateOfDeathLabel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // patientName
            // 
            this.patientName.AutoSize = true;
            this.patientName.BackColor = System.Drawing.Color.Transparent;
            this.patientName.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.patientName.Location = new System.Drawing.Point(61, 9);
            this.patientName.Name = "patientName";
            this.patientName.Size = new System.Drawing.Size(96, 16);
            this.patientName.TabIndex = 25;
            this.patientName.Text = "patientName";
            // 
            // zoneOnePanel
            // 
            this.zoneOnePanel.BackColor = System.Drawing.SystemColors.Control;
            this.zoneOnePanel.Controls.Add(this.patientDataPanel);
            this.zoneOnePanel.Controls.Add(this.DeceasedPatientTransparentIcon);
            this.zoneOnePanel.Controls.Add(this.preferredName);
            this.zoneOnePanel.Controls.Add(this.preferredNameLabel);
            this.zoneOnePanel.Controls.Add(this.patientName);
            this.zoneOnePanel.Controls.Add(this.patientPicture);
            this.zoneOnePanel.ForeColor = System.Drawing.SystemColors.ControlText;
            this.zoneOnePanel.Location = new System.Drawing.Point(3, 3);
            this.zoneOnePanel.Name = "zoneOnePanel";
            this.zoneOnePanel.Size = new System.Drawing.Size(820, 56);
            this.zoneOnePanel.TabIndex = 73;
            // 
            // patientDataPanel
            // 
            this.patientDataPanel.AutoSize = true;
            this.patientDataPanel.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.patientDataPanel.BackColor = System.Drawing.Color.Transparent;
            this.patientDataPanel.Controls.Add(this.dateOfBirthLabel);
            this.patientDataPanel.Controls.Add(this.dateOfBirthData);
            this.patientDataPanel.Controls.Add(this.genderLabel);
            this.patientDataPanel.Controls.Add(this.genderData);
            this.patientDataPanel.Controls.Add(this.btnGenderData);
            this.patientDataPanel.Controls.Add(this.identifierLabel);
            this.patientDataPanel.Controls.Add(this.identifierData);
            this.patientDataPanel.Controls.Add(this.btnIdentifierLabel);
            this.patientDataPanel.Controls.Add(this.dateOfDeathLabel);
            this.patientDataPanel.Controls.Add(this.dateOfDeathData);
            this.patientDataPanel.Controls.Add(this.ageAtDeathLabel);
            this.patientDataPanel.Controls.Add(this.ageAtDeath);
            this.patientDataPanel.ForeColor = System.Drawing.Color.Transparent;
            this.patientDataPanel.Location = new System.Drawing.Point(394, 7);
            this.patientDataPanel.Margin = new System.Windows.Forms.Padding(0);
            this.patientDataPanel.Name = "patientDataPanel";
            this.patientDataPanel.Size = new System.Drawing.Size(398, 30);
            this.patientDataPanel.TabIndex = 1;
            this.patientDataPanel.TabStop = true;
            // 
            // genderData
            // 
            this.genderData.AccessibleDescription = "Control used to show the gender";
            this.genderData.AccessibleName = "Nhs gender label";
            this.genderData.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
            this.genderData.AutoEllipsis = true;
            this.genderData.AutoSize = true;
            this.genderData.BackColor = System.Drawing.Color.Transparent;
            this.genderData.Cursor = System.Windows.Forms.Cursors.Hand;
            this.genderData.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.genderData.ForeColor = System.Drawing.SystemColors.ControlText;
            this.genderData.Location = new System.Drawing.Point(77, 0);
            this.genderData.Margin = new System.Windows.Forms.Padding(0);
            this.genderData.Name = "genderData";
            this.genderData.Padding = new System.Windows.Forms.Padding(1);
            this.genderData.Size = new System.Drawing.Size(70, 15);
            this.genderData.TabIndex = 50;
            this.genderData.Text = "Not known";
            this.genderData.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.genderData.Visible = false;
            this.genderData.MouseLeave += new System.EventHandler(this.GenderValue_MouseLeave);
            this.genderData.Click += new System.EventHandler(this.GenderValue_Click);
            this.genderData.MouseEnter += new System.EventHandler(this.GenderValue_MouseEnter);
            // 
            // btnGenderData
            // 
            this.btnGenderData.AutoSize = true;
            this.btnGenderData.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnGenderData.LinkBehavior = System.Windows.Forms.LinkBehavior.HoverUnderline;
            this.btnGenderData.LinkColor = System.Drawing.SystemColors.ControlText;
            this.btnGenderData.Location = new System.Drawing.Point(147, 0);
            this.btnGenderData.Margin = new System.Windows.Forms.Padding(0);
            this.btnGenderData.Name = "btnGenderData";
            this.btnGenderData.Padding = new System.Windows.Forms.Padding(1);
            this.btnGenderData.Size = new System.Drawing.Size(73, 15);
            this.btnGenderData.TabIndex = 2;
            this.btnGenderData.TabStop = true;
            this.btnGenderData.Text = "Gender Label";
            this.btnGenderData.MouseLeave += new System.EventHandler(this.GenderValue_MouseLeave);
            this.btnGenderData.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.GenderValue_Click);
            this.btnGenderData.Leave += new System.EventHandler(this.GenderValue_MouseLeave);
            this.btnGenderData.Enter += new System.EventHandler(this.GenderValue_MouseEnter);
            this.btnGenderData.MouseEnter += new System.EventHandler(this.GenderValue_MouseEnter);
            // 
            // identifierData
            // 
            this.identifierData.AccessibleDescription = "Control used to show the identifier or Nhs number";
            this.identifierData.AccessibleName = "Nhs identifier label";
            this.identifierData.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
            this.identifierData.AutoSize = true;
            this.identifierData.BackColor = System.Drawing.Color.Transparent;
            this.identifierData.Cursor = System.Windows.Forms.Cursors.Hand;
            this.identifierData.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.identifierData.ForeColor = System.Drawing.SystemColors.ControlText;
            this.identifierData.Location = new System.Drawing.Point(252, 0);
            this.identifierData.Margin = new System.Windows.Forms.Padding(0);
            this.identifierData.Name = "identifierData";
            this.identifierData.Padding = new System.Windows.Forms.Padding(1);
            this.identifierData.Size = new System.Drawing.Size(97, 15);
            this.identifierData.TabIndex = 51;
            this.identifierData.Text = "XXX XXX XXXX";
            this.identifierData.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.identifierData.Visible = false;
            this.identifierData.MouseLeave += new System.EventHandler(this.Identifier_MouseLeave);
            this.identifierData.Click += new System.EventHandler(this.Identifier_Click);
            this.identifierData.MouseEnter += new System.EventHandler(this.Identifier_MouseEnter);
            // 
            // btnIdentifierLabel
            // 
            this.btnIdentifierLabel.AutoSize = true;
            this.patientDataPanel.SetFlowBreak(this.btnIdentifierLabel, true);
            this.btnIdentifierLabel.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnIdentifierLabel.LinkBehavior = System.Windows.Forms.LinkBehavior.HoverUnderline;
            this.btnIdentifierLabel.LinkColor = System.Drawing.SystemColors.ControlText;
            this.btnIdentifierLabel.Location = new System.Drawing.Point(349, 0);
            this.btnIdentifierLabel.Margin = new System.Windows.Forms.Padding(0);
            this.btnIdentifierLabel.Name = "btnIdentifierLabel";
            this.btnIdentifierLabel.Padding = new System.Windows.Forms.Padding(1);
            this.btnIdentifierLabel.Size = new System.Drawing.Size(49, 15);
            this.btnIdentifierLabel.TabIndex = 3;
            this.btnIdentifierLabel.TabStop = true;
            this.btnIdentifierLabel.Text = "Identifier";
            this.btnIdentifierLabel.MouseLeave += new System.EventHandler(this.Identifier_MouseLeave);
            this.btnIdentifierLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.Identifier_Click);
            this.btnIdentifierLabel.Leave += new System.EventHandler(this.Identifier_MouseLeave);
            this.btnIdentifierLabel.Enter += new System.EventHandler(this.Identifier_MouseEnter);
            this.btnIdentifierLabel.MouseEnter += new System.EventHandler(this.Identifier_MouseEnter);
            // 
            // ageAtDeathLabel
            // 
            this.ageAtDeathLabel.AutoSize = true;
            this.ageAtDeathLabel.BackColor = System.Drawing.Color.Transparent;
            this.ageAtDeathLabel.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ageAtDeathLabel.Location = new System.Drawing.Point(33, 15);
            this.ageAtDeathLabel.Margin = new System.Windows.Forms.Padding(0);
            this.ageAtDeathLabel.Name = "ageAtDeathLabel";
            this.ageAtDeathLabel.Padding = new System.Windows.Forms.Padding(1);
            this.ageAtDeathLabel.Size = new System.Drawing.Size(2, 15);
            this.ageAtDeathLabel.TabIndex = 24;
            this.ageAtDeathLabel.Visible = false;
            // 
            // ageAtDeath
            // 
            this.ageAtDeath.AutoSize = true;
            this.ageAtDeath.BackColor = System.Drawing.Color.Transparent;
            this.ageAtDeath.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ageAtDeath.Location = new System.Drawing.Point(35, 15);
            this.ageAtDeath.Margin = new System.Windows.Forms.Padding(0);
            this.ageAtDeath.Name = "ageAtDeath";
            this.ageAtDeath.Padding = new System.Windows.Forms.Padding(1);
            this.ageAtDeath.Size = new System.Drawing.Size(2, 15);
            this.ageAtDeath.TabIndex = 25;
            this.ageAtDeath.Visible = false;
            // 
            // preferredName
            // 
            this.preferredName.AutoEllipsis = true;
            this.preferredName.BackColor = System.Drawing.Color.Transparent;
            this.preferredName.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.preferredName.Location = new System.Drawing.Point(150, 33);
            this.preferredName.Name = "preferredName";
            this.preferredName.Size = new System.Drawing.Size(0, 13);
            this.preferredName.TabIndex = 23;
            // 
            // preferredNameLabel
            // 
            this.preferredNameLabel.BackColor = System.Drawing.Color.Transparent;
            this.preferredNameLabel.Location = new System.Drawing.Point(64, 30);
            this.preferredNameLabel.Name = "preferredNameLabel";
            this.preferredNameLabel.Size = new System.Drawing.Size(79, 13);
            this.preferredNameLabel.TabIndex = 22;
            this.preferredNameLabel.Text = "Preferred name";
            // 
            // patientPicture
            // 
            this.patientPicture.BackColor = System.Drawing.Color.Transparent;
            this.patientPicture.Image = global::NhsCui.Toolkit.WinForms.Properties.Resources.NotSpecified;
            this.patientPicture.Location = new System.Drawing.Point(1, 1);
            this.patientPicture.Margin = new System.Windows.Forms.Padding(0);
            this.patientPicture.Name = "patientPicture";
            this.patientPicture.Size = new System.Drawing.Size(48, 48);
            this.patientPicture.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.patientPicture.TabIndex = 1;
            this.patientPicture.TabStop = false;
            this.patientPicture.Visible = false;
            // 
            // zoneTwoPanel
            // 
            this.zoneTwoPanel.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.zoneTwoPanel.BackColor = System.Drawing.SystemColors.Control;
            this.zoneTwoPanel.Controls.Add(this.subsectionFive);
            this.zoneTwoPanel.Controls.Add(this.viewAllergyRecordLink);
            this.zoneTwoPanel.Controls.Add(this.viewAllContactDetailsLink);
            this.zoneTwoPanel.Controls.Add(this.viewAllAddressesLink);
            this.zoneTwoPanel.Controls.Add(this.subsectionFour);
            this.zoneTwoPanel.Controls.Add(this.subsectionThree);
            this.zoneTwoPanel.Controls.Add(this.addressField);
            this.zoneTwoPanel.Controls.Add(this.phoneEmailData);
            this.zoneTwoPanel.Location = new System.Drawing.Point(3, 85);
            this.zoneTwoPanel.Name = "zoneTwoPanel";
            this.zoneTwoPanel.Size = new System.Drawing.Size(817, 81);
            this.zoneTwoPanel.TabIndex = 75;
            // 
            // subsectionFive
            // 
            this.subsectionFive.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.subsectionFive.Location = new System.Drawing.Point(630, 4);
            this.subsectionFive.Margin = new System.Windows.Forms.Padding(0);
            this.subsectionFive.Name = "subsectionFive";
            this.subsectionFive.Size = new System.Drawing.Size(187, 54);
            this.subsectionFive.TabIndex = 41;
            // 
            // viewAllergyRecordLink
            // 
            this.viewAllergyRecordLink.AutoSize = true;
            this.viewAllergyRecordLink.LinkBehavior = System.Windows.Forms.LinkBehavior.HoverUnderline;
            this.viewAllergyRecordLink.Location = new System.Drawing.Point(718, 61);
            this.viewAllergyRecordLink.Name = "viewAllergyRecordLink";
            this.viewAllergyRecordLink.Size = new System.Drawing.Size(96, 13);
            this.viewAllergyRecordLink.TabIndex = 6;
            this.viewAllergyRecordLink.TabStop = true;
            this.viewAllergyRecordLink.Text = "View allergy record";
            this.viewAllergyRecordLink.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.ViewAllergyRecord_Click);
            this.viewAllergyRecordLink.Click += new System.EventHandler(this.ViewAllergyRecord_Click);
            // 
            // viewAllContactDetailsLink
            // 
            this.viewAllContactDetailsLink.AutoSize = true;
            this.viewAllContactDetailsLink.LinkBehavior = System.Windows.Forms.LinkBehavior.HoverUnderline;
            this.viewAllContactDetailsLink.Location = new System.Drawing.Point(303, 65);
            this.viewAllContactDetailsLink.Name = "viewAllContactDetailsLink";
            this.viewAllContactDetailsLink.Size = new System.Drawing.Size(115, 13);
            this.viewAllContactDetailsLink.TabIndex = 5;
            this.viewAllContactDetailsLink.TabStop = true;
            this.viewAllContactDetailsLink.Text = "View all contact details";
            this.viewAllContactDetailsLink.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.ViewAllContactDetails_Click);
            this.viewAllContactDetailsLink.Click += new System.EventHandler(this.ViewAllContactDetails_Click);
            // 
            // viewAllAddressesLink
            // 
            this.viewAllAddressesLink.AutoSize = true;
            this.viewAllAddressesLink.LinkBehavior = System.Windows.Forms.LinkBehavior.HoverUnderline;
            this.viewAllAddressesLink.Location = new System.Drawing.Point(115, 65);
            this.viewAllAddressesLink.Name = "viewAllAddressesLink";
            this.viewAllAddressesLink.Size = new System.Drawing.Size(94, 13);
            this.viewAllAddressesLink.TabIndex = 4;
            this.viewAllAddressesLink.TabStop = true;
            this.viewAllAddressesLink.Text = "View all addresses";
            this.viewAllAddressesLink.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.ViewAllAddresses_Click);
            this.viewAllAddressesLink.Click += new System.EventHandler(this.ViewAllAddresses_Click);
            // 
            // subsectionFour
            // 
            this.subsectionFour.Location = new System.Drawing.Point(531, 0);
            this.subsectionFour.Name = "subsectionFour";
            this.subsectionFour.Size = new System.Drawing.Size(94, 74);
            this.subsectionFour.TabIndex = 40;
            // 
            // subsectionThree
            // 
            this.subsectionThree.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.subsectionThree.Location = new System.Drawing.Point(426, 0);
            this.subsectionThree.Name = "subsectionThree";
            this.subsectionThree.Size = new System.Drawing.Size(94, 74);
            this.subsectionThree.TabIndex = 39;
            // 
            // addressField
            // 
            this.addressField.AccessibleDescription = "Control used to show the address";
            this.addressField.AccessibleName = "Nhs address label";
            this.addressField.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
            this.addressField.AddressType = "Usual address:";
            this.addressField.AddressTypeLabelFont = null;
            this.addressField.AutoSize = true;
            this.addressField.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.addressField.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addressField.Location = new System.Drawing.Point(0, 0);
            this.addressField.Name = "addressField";
            this.addressField.Size = new System.Drawing.Size(206, 64);
            this.addressField.TabIndex = 27;
            this.addressField.TooltipText = "";
            // 
            // phoneEmailData
            // 
            this.phoneEmailData.AccessibleDescription = "Control used to show the contact details";
            this.phoneEmailData.AccessibleName = "Nhs contact label";
            this.phoneEmailData.AccessibleRole = System.Windows.Forms.AccessibleRole.StaticText;
            this.phoneEmailData.AutoSize = true;
            this.phoneEmailData.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.phoneEmailData.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.phoneEmailData.Location = new System.Drawing.Point(199, 0);
            this.phoneEmailData.Name = "phoneEmailData";
            this.phoneEmailData.Size = new System.Drawing.Size(220, 52);
            this.phoneEmailData.TabIndex = 25;
            this.phoneEmailData.TooltipText = "";
            // 
            // zoneOneHeaderStripPanel
            // 
            this.zoneOneHeaderStripPanel.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.zoneOneHeaderStripPanel.BackColor = System.Drawing.SystemColors.Control;
            this.zoneOneHeaderStripPanel.Controls.Add(this.contactDetailsPreviewLabel);
            this.zoneOneHeaderStripPanel.Controls.Add(this.allergyIcon);
            this.zoneOneHeaderStripPanel.Controls.Add(this.allergiesInformationLabel);
            this.zoneOneHeaderStripPanel.Controls.Add(this.subsectionFourTitle);
            this.zoneOneHeaderStripPanel.Controls.Add(this.subsectionThreeTitle);
            this.zoneOneHeaderStripPanel.Controls.Add(this.toggleDropButton);
            this.zoneOneHeaderStripPanel.Controls.Add(this.subsectionTwoTitleLabel);
            this.zoneOneHeaderStripPanel.Controls.Add(this.subsectionOneTitleLabel);
            this.zoneOneHeaderStripPanel.Controls.Add(this.addressPreviewLabel);
            this.zoneOneHeaderStripPanel.Location = new System.Drawing.Point(3, 62);
            this.zoneOneHeaderStripPanel.Name = "zoneOneHeaderStripPanel";
            this.zoneOneHeaderStripPanel.Padding = new System.Windows.Forms.Padding(3);
            this.zoneOneHeaderStripPanel.Size = new System.Drawing.Size(420, 27);
            this.zoneOneHeaderStripPanel.TabIndex = 74;
            this.zoneOneHeaderStripPanel.MouseLeave += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseLeave);
            this.zoneOneHeaderStripPanel.Click += new System.EventHandler(this.ToggleDropButton_Click);
            this.zoneOneHeaderStripPanel.MouseEnter += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseEnter);
            // 
            // contactDetailsPreviewLabel
            // 
            this.contactDetailsPreviewLabel.AutoEllipsis = true;
            this.contactDetailsPreviewLabel.Location = new System.Drawing.Point(180, 11);
            this.contactDetailsPreviewLabel.Name = "contactDetailsPreviewLabel";
            this.contactDetailsPreviewLabel.Size = new System.Drawing.Size(0, 13);
            this.contactDetailsPreviewLabel.TabIndex = 39;
            this.contactDetailsPreviewLabel.MouseLeave += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseLeave);
            this.contactDetailsPreviewLabel.Click += new System.EventHandler(this.ToggleDropButton_Click);
            this.contactDetailsPreviewLabel.MouseEnter += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseEnter);
            // 
            // allergyIcon
            // 
            this.allergyIcon.AutoEllipsis = true;
            this.allergyIcon.FlatAppearance.BorderSize = 0;
            this.allergyIcon.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.allergyIcon.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.allergyIcon.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.allergyIcon.Image = global::NhsCui.Toolkit.WinForms.Properties.Resources.arrow_down;
            this.allergyIcon.Location = new System.Drawing.Point(306, 0);
            this.allergyIcon.Margin = new System.Windows.Forms.Padding(0);
            this.allergyIcon.Name = "allergyIcon";
            this.allergyIcon.Size = new System.Drawing.Size(16, 16);
            this.allergyIcon.TabIndex = 38;
            this.allergyIcon.TabStop = false;
            this.allergyIcon.UseVisualStyleBackColor = true;
            this.allergyIcon.MouseLeave += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseLeave);
            this.allergyIcon.Click += new System.EventHandler(this.ToggleDropButton_Click);
            this.allergyIcon.MouseEnter += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseEnter);
            // 
            // allergiesInformationLabel
            // 
            this.allergiesInformationLabel.AutoEllipsis = true;
            this.allergiesInformationLabel.Location = new System.Drawing.Point(300, 6);
            this.allergiesInformationLabel.Name = "allergiesInformationLabel";
            this.allergiesInformationLabel.Size = new System.Drawing.Size(0, 13);
            this.allergiesInformationLabel.TabIndex = 0;
            this.allergiesInformationLabel.MouseLeave += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseLeave);
            this.allergiesInformationLabel.Click += new System.EventHandler(this.ToggleDropButton_Click);
            this.allergiesInformationLabel.MouseEnter += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseEnter);
            // 
            // subsectionFourTitle
            // 
            this.subsectionFourTitle.AutoEllipsis = true;
            this.subsectionFourTitle.Location = new System.Drawing.Point(265, 7);
            this.subsectionFourTitle.Name = "subsectionFourTitle";
            this.subsectionFourTitle.Size = new System.Drawing.Size(0, 13);
            this.subsectionFourTitle.TabIndex = 0;
            this.subsectionFourTitle.MouseLeave += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseLeave);
            this.subsectionFourTitle.Click += new System.EventHandler(this.ToggleDropButton_Click);
            this.subsectionFourTitle.MouseEnter += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseEnter);
            // 
            // subsectionThreeTitle
            // 
            this.subsectionThreeTitle.AutoEllipsis = true;
            this.subsectionThreeTitle.Location = new System.Drawing.Point(224, 5);
            this.subsectionThreeTitle.Name = "subsectionThreeTitle";
            this.subsectionThreeTitle.Size = new System.Drawing.Size(0, 13);
            this.subsectionThreeTitle.TabIndex = 0;
            this.subsectionThreeTitle.MouseLeave += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseLeave);
            this.subsectionThreeTitle.Click += new System.EventHandler(this.ToggleDropButton_Click);
            this.subsectionThreeTitle.MouseEnter += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseEnter);
            // 
            // toggleDropButton
            // 
            this.toggleDropButton.BackColor = System.Drawing.Color.Transparent;
            this.toggleDropButton.FlatAppearance.BorderSize = 0;
            this.toggleDropButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.Transparent;
            this.toggleDropButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Transparent;
            this.toggleDropButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.toggleDropButton.ImageIndex = 1;
            this.toggleDropButton.ImageList = this.toggleImageList;
            this.toggleDropButton.Location = new System.Drawing.Point(394, 0);
            this.toggleDropButton.Margin = new System.Windows.Forms.Padding(0);
            this.toggleDropButton.Name = "toggleDropButton";
            this.toggleDropButton.Size = new System.Drawing.Size(20, 20);
            this.toggleDropButton.TabIndex = 3;
            this.toggleDropButton.UseVisualStyleBackColor = false;
            this.toggleDropButton.MouseLeave += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseLeave);
            this.toggleDropButton.Click += new System.EventHandler(this.ToggleDropButton_Click);
            this.toggleDropButton.MouseEnter += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseEnter);
            // 
            // subsectionTwoTitleLabel
            // 
            this.subsectionTwoTitleLabel.AutoEllipsis = true;
            this.subsectionTwoTitleLabel.Location = new System.Drawing.Point(177, 3);
            this.subsectionTwoTitleLabel.Margin = new System.Windows.Forms.Padding(3);
            this.subsectionTwoTitleLabel.Name = "subsectionTwoTitleLabel";
            this.subsectionTwoTitleLabel.Size = new System.Drawing.Size(0, 13);
            this.subsectionTwoTitleLabel.TabIndex = 35;
            this.subsectionTwoTitleLabel.MouseLeave += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseLeave);
            this.subsectionTwoTitleLabel.Click += new System.EventHandler(this.ToggleDropButton_Click);
            this.subsectionTwoTitleLabel.MouseEnter += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseEnter);
            // 
            // subsectionOneTitleLabel
            // 
            this.subsectionOneTitleLabel.AutoEllipsis = true;
            this.subsectionOneTitleLabel.Location = new System.Drawing.Point(6, 6);
            this.subsectionOneTitleLabel.Margin = new System.Windows.Forms.Padding(3);
            this.subsectionOneTitleLabel.Name = "subsectionOneTitleLabel";
            this.subsectionOneTitleLabel.Size = new System.Drawing.Size(0, 13);
            this.subsectionOneTitleLabel.TabIndex = 36;
            this.subsectionOneTitleLabel.MouseLeave += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseLeave);
            this.subsectionOneTitleLabel.Click += new System.EventHandler(this.ToggleDropButton_Click);
            this.subsectionOneTitleLabel.MouseEnter += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseEnter);
            // 
            // addressPreviewLabel
            // 
            this.addressPreviewLabel.AutoEllipsis = true;
            this.addressPreviewLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addressPreviewLabel.Location = new System.Drawing.Point(82, 6);
            this.addressPreviewLabel.Margin = new System.Windows.Forms.Padding(3);
            this.addressPreviewLabel.Name = "addressPreviewLabel";
            this.addressPreviewLabel.Size = new System.Drawing.Size(68, 13);
            this.addressPreviewLabel.TabIndex = 37;
            this.addressPreviewLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addressPreviewLabel.MouseLeave += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseLeave);
            this.addressPreviewLabel.Click += new System.EventHandler(this.ToggleDropButton_Click);
            this.addressPreviewLabel.MouseEnter += new System.EventHandler(this.ZoneOneHeaderStripPanel_MouseEnter);
            // 
            // borderPanel
            // 
            this.borderPanel.BackColor = System.Drawing.SystemColors.WindowFrame;
            this.borderPanel.ForeColor = System.Drawing.SystemColors.ControlText;
            this.borderPanel.Location = new System.Drawing.Point(452, 66);
            this.borderPanel.Name = "borderPanel";
            this.borderPanel.Padding = new System.Windows.Forms.Padding(2);
            this.borderPanel.Size = new System.Drawing.Size(10, 10);
            this.borderPanel.TabIndex = 38;
            // 
            // allergyIconsImageList
            // 
            this.allergyIconsImageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("allergyIconsImageList.ImageStream")));
            this.allergyIconsImageList.TransparentColor = System.Drawing.Color.Transparent;
            this.allergyIconsImageList.Images.SetKeyName(0, "AllergiesNotPresentIcon.gif");
            this.allergyIconsImageList.Images.SetKeyName(1, "AllergiesPresentIcon.gif");
            this.allergyIconsImageList.Images.SetKeyName(2, "AllergiesUnavailable.gif");
            // 
            // subsectionOneBorder
            // 
            this.subsectionOneBorder.BackColor = System.Drawing.SystemColors.WindowFrame;
            this.subsectionOneBorder.Location = new System.Drawing.Point(530, 65);
            this.subsectionOneBorder.Name = "subsectionOneBorder";
            this.subsectionOneBorder.Size = new System.Drawing.Size(10, 10);
            this.subsectionOneBorder.TabIndex = 39;
            // 
            // subsectionTwoBorder
            // 
            this.subsectionTwoBorder.BackColor = System.Drawing.SystemColors.WindowFrame;
            this.subsectionTwoBorder.Location = new System.Drawing.Point(552, 66);
            this.subsectionTwoBorder.Name = "subsectionTwoBorder";
            this.subsectionTwoBorder.Size = new System.Drawing.Size(10, 10);
            this.subsectionTwoBorder.TabIndex = 40;
            // 
            // subsectionThreeBorder
            // 
            this.subsectionThreeBorder.BackColor = System.Drawing.SystemColors.WindowFrame;
            this.subsectionThreeBorder.Location = new System.Drawing.Point(568, 66);
            this.subsectionThreeBorder.Name = "subsectionThreeBorder";
            this.subsectionThreeBorder.Size = new System.Drawing.Size(10, 10);
            this.subsectionThreeBorder.TabIndex = 41;
            // 
            // subsectionFourBorder
            // 
            this.subsectionFourBorder.BackColor = System.Drawing.SystemColors.WindowFrame;
            this.subsectionFourBorder.Location = new System.Drawing.Point(591, 65);
            this.subsectionFourBorder.Name = "subsectionFourBorder";
            this.subsectionFourBorder.Size = new System.Drawing.Size(10, 10);
            this.subsectionFourBorder.TabIndex = 40;
            // 
            // expandCollpaseImageBorder
            // 
            this.expandCollpaseImageBorder.BackColor = System.Drawing.SystemColors.WindowFrame;
            this.expandCollpaseImageBorder.Location = new System.Drawing.Point(607, 66);
            this.expandCollpaseImageBorder.Name = "expandCollpaseImageBorder";
            this.expandCollpaseImageBorder.Size = new System.Drawing.Size(10, 10);
            this.expandCollpaseImageBorder.TabIndex = 42;
            // 
            // PatientBanner
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.Controls.Add(this.expandCollpaseImageBorder);
            this.Controls.Add(this.subsectionFourBorder);
            this.Controls.Add(this.subsectionThreeBorder);
            this.Controls.Add(this.subsectionTwoBorder);
            this.Controls.Add(this.subsectionOneBorder);
            this.Controls.Add(this.zoneOneHeaderStripPanel);
            this.Controls.Add(this.zoneTwoPanel);
            this.Controls.Add(this.zoneOnePanel);
            this.Controls.Add(this.borderPanel);
            this.Name = "PatientBanner";
            this.Size = new System.Drawing.Size(826, 169);
            this.Load += new System.EventHandler(this.PatientBanner_Load);
            this.FontChanged += new System.EventHandler(this.PatientBanner_FontChanged);
            ((System.ComponentModel.ISupportInitialize)(this.DeceasedPatientTransparentIcon)).EndInit();
            this.zoneOnePanel.ResumeLayout(false);
            this.zoneOnePanel.PerformLayout();
            this.patientDataPanel.ResumeLayout(false);
            this.patientDataPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.identifierData)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.patientPicture)).EndInit();
            this.zoneTwoPanel.ResumeLayout(false);
            this.zoneTwoPanel.PerformLayout();
            this.zoneOneHeaderStripPanel.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion


        #endregion

        internal System.Windows.Forms.Panel zoneOnePanel;
        internal System.Windows.Forms.Panel zoneTwoPanel;
        internal System.Windows.Forms.Panel zoneOneHeaderStripPanel;
        internal System.Windows.Forms.PictureBox patientPicture;
        internal System.Windows.Forms.Label patientName;
        internal IdentifierLabel identifierData;
        internal System.Windows.Forms.Label identifierLabel;
        internal System.Windows.Forms.Label genderLabel;
        internal GenderLabel genderData;
        internal System.Windows.Forms.Label dateOfBirthData;
        internal System.Windows.Forms.Label dateOfBirthLabel;
        internal System.Windows.Forms.Label dateOfDeathData;
        internal System.Windows.Forms.Label dateOfDeathLabel;
        internal AddressLabel addressField;
        internal ContactLabel phoneEmailData;
        internal System.Windows.Forms.Button toggleDropButton;
        internal System.Windows.Forms.Label subsectionTwoTitleLabel;
        internal System.Windows.Forms.Label subsectionOneTitleLabel;
        internal System.Windows.Forms.Label addressPreviewLabel;
        internal System.Windows.Forms.Panel borderPanel;
        internal System.Windows.Forms.Panel subsectionFive;
        internal System.Windows.Forms.Label subsectionThreeTitle;
        internal System.Windows.Forms.Panel subsectionFour;
        internal System.Windows.Forms.Label subsectionFourTitle;
        internal System.Windows.Forms.Label allergiesInformationLabel;
        internal System.Windows.Forms.Panel subsectionThree;
        internal System.Windows.Forms.Label preferredNameLabel;
        internal System.Windows.Forms.Label preferredName;
        internal System.Windows.Forms.LinkLabel viewAllAddressesLink;
        internal System.Windows.Forms.LinkLabel viewAllContactDetailsLink;
        internal System.Windows.Forms.LinkLabel viewAllergyRecordLink;
        private System.Windows.Forms.ImageList allergyIconsImageList;
        internal System.Windows.Forms.Button allergyIcon;
        private System.Windows.Forms.Label contactDetailsPreviewLabel;
        private System.Windows.Forms.Label ageAtDeath;
        private System.Windows.Forms.Label ageAtDeathLabel;
        private System.Windows.Forms.Panel subsectionOneBorder;
        private System.Windows.Forms.Panel subsectionTwoBorder;
        private System.Windows.Forms.Panel subsectionThreeBorder;
        private System.Windows.Forms.Panel subsectionFourBorder;
        private System.Windows.Forms.Panel expandCollpaseImageBorder;
        private System.Windows.Forms.PictureBox DeceasedPatientTransparentIcon;
        private System.Windows.Forms.FlowLayoutPanel patientDataPanel;
        private System.Windows.Forms.LinkLabel btnGenderData;
        private System.Windows.Forms.LinkLabel btnIdentifierLabel;
    }
}
