//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class ComponentsMedicationsListView {
    
    /// <summary>
    /// PageTitleControl1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Microsoft.Cui.SampleWebsite.PageTitleControl PageTitleControl1;
    
    /// <summary>
    /// Tabs control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.TabContainer Tabs;
    
    /// <summary>
    /// panelSilverlightControl control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.TabPanel panelSilverlightControl;
    
    /// <summary>
    /// DemoPanel1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel DemoPanel1;
    
    /// <summary>
    /// patientSelectText control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label patientSelectText;
    
    /// <summary>
    /// matchOptions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel matchOptions;
    
    /// <summary>
    /// patientListBox control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ListBox patientListBox;
    
    /// <summary>
    /// patientBanner control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::NhsCui.Toolkit.Web.PatientBanner patientBanner;
    
    /// <summary>
    /// Properties_HeaderPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel Properties_HeaderPanel;
    
    /// <summary>
    /// properties_ToggleImage control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputImage properties_ToggleImage;
    
    /// <summary>
    /// Properties_ContentPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel Properties_ContentPanel;
    
    /// <summary>
    /// cpeProperties control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeProperties;
    
    /// <summary>
    /// AdditionalInfo_HeaderPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel AdditionalInfo_HeaderPanel;
    
    /// <summary>
    /// AdditionalInfo_ToggleImage control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputImage AdditionalInfo_ToggleImage;
    
    /// <summary>
    /// AdditionalInfo_ContentPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel AdditionalInfo_ContentPanel;
    
    /// <summary>
    /// cpeAdditionalInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeAdditionalInfo;
    
    /// <summary>
    /// UsageHints_HeaderPanel1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel UsageHints_HeaderPanel1;
    
    /// <summary>
    /// UsageHints_ToggleImage1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputImage UsageHints_ToggleImage1;
    
    /// <summary>
    /// UsageHints_ContentPanel1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel UsageHints_ContentPanel1;
    
    /// <summary>
    /// CollapsiblePanelExtenderUsageHints_1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.CollapsiblePanelExtender CollapsiblePanelExtenderUsageHints_1;
    
    /// <summary>
    /// UsageHints_HeaderPanel2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel UsageHints_HeaderPanel2;
    
    /// <summary>
    /// UsageHints_ToggleImage2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputImage UsageHints_ToggleImage2;
    
    /// <summary>
    /// UsageHints_ContentPanel2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel UsageHints_ContentPanel2;
    
    /// <summary>
    /// CollapsiblePanelExtenderUsageHints_2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.CollapsiblePanelExtender CollapsiblePanelExtenderUsageHints_2;
    
    /// <summary>
    /// UsageHints_HeaderPanel3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel UsageHints_HeaderPanel3;
    
    /// <summary>
    /// UsageHints_ToggleImage3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputImage UsageHints_ToggleImage3;
    
    /// <summary>
    /// UsageHints_ContentPanel3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel UsageHints_ContentPanel3;
    
    /// <summary>
    /// CollapsiblePanelExtenderUsageHints_3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.CollapsiblePanelExtender CollapsiblePanelExtenderUsageHints_3;
    
    /// <summary>
    /// UsageHints_HeaderPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel UsageHints_HeaderPanel;
    
    /// <summary>
    /// UsageHints_ToggleImage control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputImage UsageHints_ToggleImage;
    
    /// <summary>
    /// UsageHints_ContentPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel UsageHints_ContentPanel;
    
    /// <summary>
    /// cpeUsageHints control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeUsageHints;
    
    /// <summary>
    /// panelWPF control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.TabPanel panelWPF;
}
