//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class SingleConceptMatching {
    
    /// <summary>
    /// PageTitleControl1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Microsoft.Cui.SampleWebsite.PageTitleControl PageTitleControl1;
    
    /// <summary>
    /// Tabs control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.TabContainer Tabs;
    
    /// <summary>
    /// panelSilverlightControl control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.TabPanel panelSilverlightControl;
    
    /// <summary>
    /// DemoPanel1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel DemoPanel1;
    
    /// <summary>
    /// Scenarios_HeaderPanelSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel Scenarios_HeaderPanelSingleConcept;
    
    /// <summary>
    /// Scenarios_ToggleImageSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputImage Scenarios_ToggleImageSingleConcept;
    
    /// <summary>
    /// Scenarios_ContentPanelSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel Scenarios_ContentPanelSingleConcept;
    
    /// <summary>
    /// cpeScenariosSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeScenariosSingleConcept;
    
    /// <summary>
    /// DesignNotes_HeaderPanelSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel DesignNotes_HeaderPanelSingleConcept;
    
    /// <summary>
    /// DesignNotes_ToggleImageSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputImage DesignNotes_ToggleImageSingleConcept;
    
    /// <summary>
    /// DesignNotes_ContentPanelSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel DesignNotes_ContentPanelSingleConcept;
    
    /// <summary>
    /// cpeDesignNotesSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeDesignNotesSingleConcept;
    
    /// <summary>
    /// Header_GettingStarted control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel Header_GettingStarted;
    
    /// <summary>
    /// ToggleImage_GettingStartedAccordion control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputImage ToggleImage_GettingStartedAccordion;
    
    /// <summary>
    /// Content_GettingStarted control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel Content_GettingStarted;
    
    /// <summary>
    /// cpeGettingStarted control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeGettingStarted;
    
    /// <summary>
    /// Properties_HeaderPanelSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel Properties_HeaderPanelSingleConcept;
    
    /// <summary>
    /// Prop_ToggleImageSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputImage Prop_ToggleImageSingleConcept;
    
    /// <summary>
    /// Properties_ContentPanelSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel Properties_ContentPanelSingleConcept;
    
    /// <summary>
    /// cpePropertiesSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.CollapsiblePanelExtender cpePropertiesSingleConcept;
    
    /// <summary>
    /// ConsumingTheControl_HeaderPanelSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel ConsumingTheControl_HeaderPanelSingleConcept;
    
    /// <summary>
    /// ConsumingTheControl_ToggleImageSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputImage ConsumingTheControl_ToggleImageSingleConcept;
    
    /// <summary>
    /// ConsumingTheControl_ContentPanelSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel ConsumingTheControl_ContentPanelSingleConcept;
    
    /// <summary>
    /// cpeConsumingTheControlSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeConsumingTheControlSingleConcept;
    
    /// <summary>
    /// ConfiguringSubsets_HeaderPanelSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel ConfiguringSubsets_HeaderPanelSingleConcept;
    
    /// <summary>
    /// ConfiguringSubsets_ToggleImageSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputImage ConfiguringSubsets_ToggleImageSingleConcept;
    
    /// <summary>
    /// ConfiguringSubsets_ContentPanelSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel ConfiguringSubsets_ContentPanelSingleConcept;
    
    /// <summary>
    /// cpeConfiguringSubsetsSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeConfiguringSubsetsSingleConcept;
    
    /// <summary>
    /// InitiatingSearch_HeaderPanelSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel InitiatingSearch_HeaderPanelSingleConcept;
    
    /// <summary>
    /// InitiatingSearch_ToggleImageSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputImage InitiatingSearch_ToggleImageSingleConcept;
    
    /// <summary>
    /// InitiatingSearch_ContentPanelSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel InitiatingSearch_ContentPanelSingleConcept;
    
    /// <summary>
    /// cpeInitiatingSearchSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeInitiatingSearchSingleConcept;
    
    /// <summary>
    /// ParsingText_HeaderPanelSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel ParsingText_HeaderPanelSingleConcept;
    
    /// <summary>
    /// ParsingText_ToggleImageSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputImage ParsingText_ToggleImageSingleConcept;
    
    /// <summary>
    /// ParsingText_ContentPanelSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel ParsingText_ContentPanelSingleConcept;
    
    /// <summary>
    /// cpeParsingTextSingleConcept control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.CollapsiblePanelExtender cpeParsingTextSingleConcept;
    
    /// <summary>
    /// panelWPF control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.TabPanel panelWPF;
}
