//-----------------------------------------------------------------------
// <copyright file="MedicationNameLabelTest.cs" company="Microsoft Corporation and Crown copyright 2007 - 2010.">
// Copyright (c) Microsoft Corporation and Crown copyright 2007 - 2010.
// All rights reserved.
//
// CERTAIN PARTS OF THIS WORK CONTAIN SOFTWARE CODE THAT IS LICENSED 
// FOR USE UNDER THE MICROSOFT PUBLIC LICENSE. DISTRIBUTION, IN SOURCE CODE 
// OR OBJECT CODE FORM, OF THOSE PARTS MUST COMPLY WITH THE TERMS OF THE 
// PUBLIC LICENSE. SEE http://www.microsoft.com/opensource/licenses.mspx 
// FOR DETAILS.  
// IF YOU BRING A PATENT CLAIM AGAINST ANY CONTRIBUTOR OVER PATENTS THAT 
// YOU CLAIM ARE INFRINGED BY THE PUBLIC LICENSE SOFTWARE, YOUR PATENT 
// LICENSE FROM SUCH CONTRIBUTOR TO THE SOFTWARE ENDS AUTOMATICALLY.
//
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
// </copyright>
// <date>02-Feb-2007</date>
// <summary>
// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
// </summary>
//-----------------------------------------------------------------------
namespace NhsCui.Toolkit.Web.Test
{
    #region Using
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using System;
    using System.Text;
    using System.Collections.Generic;
    using NhsCui.Toolkit.Web;
    using System.ComponentModel;
    using System.Web.UI;
    using System.Threading;
    using System.IO;
    #endregion

    /// <summary>
    /// This is a test class for NhsCui.Toolkit.Web.MedicationNameLabel and is intended
    /// to contain all NhsCui.Toolkit.Web.MedicationNameLabel Unit Tests
    ///</summary>
    [TestClass()]
    public class MedicationNameLabelTest : IDisposable
    {
        /// <summary>
        /// Test Context Instance
        /// </summary>
        private TestContext testContextInstance;

        /// <summary>
        /// Reset event to indicate that the propertychanged event was raised
        /// </summary>
        private ManualResetEvent propertyChangedThreadEvent = new ManualResetEvent(false);

        /// <summary>
        /// Name of property reported by the property changed event
        /// </summary>
        private string changedPropertyName;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return this.testContextInstance;
            }

            set
            {
                this.testContextInstance = value;
            }
        }

        #region Additional test attributes
        // You can use the following additional attributes as you write your tests:        
        // Use ClassInitialize to run code before running the first test in the class        
        // [ClassInitialize()]
        // public static void MyClassInitialize(TestContext testContext)
        // {
        // }
        // Use ClassCleanup to run code after all tests in a class have run
        // [ClassCleanup()]
        // public static void MyClassCleanup()
        // {
        // }
        // Use TestInitialize to run code before running each test
        // [TestInitialize()]
        // public void MyTestInitialize()
        // {
        // }
        // Use TestCleanup to run code after each test has run
        // [TestCleanup()]
        // public void MyTestCleanup()
        // {
        // }
        #endregion

        /// <summary>
        ///A test for CriticalAlertGraphic
        ///</summary>
        [TestMethod()]
        public void CriticalAlertGraphicTest()
        {
            MedicationNameLabel target = new MedicationNameLabel();

            string val = "~/images/test.png"; 
            target.CriticalAlertGraphic = val;
            Assert.AreEqual(val, target.CriticalAlertGraphic, "NhsCui.Toolkit.Web.MedicationNameLabel.CriticalAlertGraphic was not set correctly.");            
        }

        /// <summary>
        ///A test for DrugNameStyle
        ///</summary>
        [TestMethod()]
        public void DrugNameStyleTest()
        {
            MedicationNameLabel target = new MedicationNameLabel();

            string val = "drugNameStyle"; 

            target.DrugNameStyle = val;

            Assert.AreEqual(val, target.DrugNameStyle, "NhsCui.Toolkit.Web.MedicationNameLabel.DrugNameStyle was not set correctly.");            
        }

        /// <summary>
        ///A test for IndicatorGraphic
        ///</summary>
        [TestMethod()]
        public void IndicatorGraphicTest()
        {
            MedicationNameLabel target = new MedicationNameLabel();

            string val = "~/images/test.png"; 

            target.IndicatorGraphic = val;
            Assert.AreEqual(val, target.IndicatorGraphic, "NhsCui.Toolkit.Web.MedicationNameLabel.IndicatorGraphic was not set correctly.");
        }

        /// <summary>
        ///A test for MedicationNames
        ///</summary>
        [TestMethod()]
        public void MedicationNamesTest()
        {
            MedicationNameLabel target = new MedicationNameLabel();
            MedicationName item = new MedicationName("Name", "Info");
            target.MedicationNames.Add(item);

            Assert.AreEqual(item, target.MedicationNames[0], "NhsCui.Toolkit.Web.MedicationNameLabel.MedicationNames was not set correctly.");            
        }

        /// <summary>
        ///A test for OnPropertyChanged (PropertyChangedEventArgs)
        ///</summary>
        [DeploymentItem("NhsCui.Toolkit.Web.dll")]
        [TestMethod()]
        public void OnPropertyChangedTest()
        {
            MedicationNameLabel target = new MedicationNameLabel();            
            
            target.CriticalAlertGraphic = "";
            target.DrugNameStyle = "";
            target.ShowGraphics = false;
            target.MedicationNames.Add(new MedicationName("Name", "Info"));

            target.PropertyChanged += new System.ComponentModel.PropertyChangedEventHandler(this.OnPropertyChanged);
            this.propertyChangedThreadEvent.Reset();

            target.CriticalAlertGraphic = "~/image/test.png";
            if (!this.propertyChangedThreadEvent.WaitOne(500, false))
            {
                Assert.Fail("Property Changed event was not raised for CriticalAlertGraphic Property");
            }
            else
            {
                Assert.AreEqual<string>(this.changedPropertyName, "CriticalAlertGraphic");
            }

            target.DrugNameStyle = "~/image/test.png";
            if (!this.propertyChangedThreadEvent.WaitOne(500, false))
            {
                Assert.Fail("Property Changed event was not raised for DrugNameStyle Property");
            }
            else
            {
                Assert.AreEqual<string>(this.changedPropertyName, "DrugNameStyle");
            }

            target.ShowGraphics = true;
            if (!this.propertyChangedThreadEvent.WaitOne(500, false))
            {
                Assert.Fail("Property Changed event was not raised for ShowGraphics Property");
            }
            else
            {
                Assert.AreEqual<string>(this.changedPropertyName, "ShowGraphics");
            }

            target.MedicationNames[0].Name = "NewName";
            if (!this.propertyChangedThreadEvent.WaitOne(500, false))
            {
                Assert.Fail("Property Changed event was not raised for MedicationName Name Property");
            }
            else
            {
                Assert.AreEqual<string>(this.changedPropertyName, "Name");
            }

            target.MedicationNames[0].Information = "NewInfo";
            if (!this.propertyChangedThreadEvent.WaitOne(500, false))
            {
                Assert.Fail("Property Changed event was not raised for MedicationName Info Property");
            }
            else
            {
                Assert.AreEqual<string>(this.changedPropertyName, "Information");
            }

            this.propertyChangedThreadEvent.Close();
        }

        /// <summary>
        ///A test for ShowGraphics
        ///</summary>
        [TestMethod()]
        public void ShowGraphicsTest()
        {
            MedicationNameLabel target = new MedicationNameLabel();

            bool val = false; // TODO: Assign to an appropriate value for the property

            target.ShowGraphics = val;

            Assert.AreEqual(val, target.ShowGraphics, "NhsCui.Toolkit.Web.MedicationNameLabel.ShowGraphics was not set correctly.");            
        }

        /// <summary>
        /// Ensure that the Change Event is cleaned up
        /// </summary>
        [TestCleanup()]
        public void Cleanup()
        {
            this.propertyChangedThreadEvent.Close();
        }

        #region IDisposable Members
        /// <summary>
        /// Clean up Property Changed Event
        /// </summary>
        public void Dispose()
        {
            this.Dispose(true);
            GC.SuppressFinalize(this);
        }

        /// <summary>
        /// Dispose
        /// </summary>
        /// <param name="disposing">Dispose</param>
        protected virtual void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (this.propertyChangedThreadEvent != null)
                {
                    this.propertyChangedThreadEvent.Close();
                }
            }
        }
        #endregion

        /// <summary>
        /// Event Handler for Property Changed Event
        /// </summary>
        /// <param name="sender">Sender</param>
        /// <param name="e">Property Changed Event</param>
        private void OnPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            this.changedPropertyName = e.PropertyName;
            this.propertyChangedThreadEvent.Set();
        }
    }
}
