// <auto-generated />
//-----------------------------------------------------------------------
// <copyright file="Default.aspx.cs" company="Microsoft Corporation and Crown copyright 2007 - 2010.">
// Copyright (c) Microsoft Corporation and Crown copyright 2007 - 2010.
// All rights reserved.
//
// CERTAIN PARTS OF THIS WORK CONTAIN SOFTWARE CODE THAT IS LICENSED 
// FOR USE UNDER THE MICROSOFT PUBLIC LICENSE. DISTRIBUTION, IN SOURCE CODE 
// OR OBJECT CODE FORM, OF THOSE PARTS MUST COMPLY WITH THE TERMS OF THE 
// PUBLIC LICENSE. SEE http://www.microsoft.com/opensource/licenses.mspx 
// FOR DETAILS.  
// IF YOU BRING A PATENT CLAIM AGAINST ANY CONTRIBUTOR OVER PATENTS THAT 
// YOU CLAIM ARE INFRINGED BY THE PUBLIC LICENSE SOFTWARE, YOUR PATENT 
// LICENSE FROM SUCH CONTRIBUTOR TO THE SOFTWARE ENDS AUTOMATICALLY.
//
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
// </copyright>
// <date>03-Jan-2007</date>
// <summary>Default page for test harness</summary>
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.UI;
using System.Text;

public partial class Automated_TestHarness : Page
{
    /// <summary>
    /// Populate the array of Test Suite Urls
    /// </summary>
    protected void Page_Load(object sender, EventArgs e)
    {
        // Create the list of test suites and add the basics first
        List<string> testSuites = new List<string>();
        testSuites.Add("'TestHarnessTests.aspx'");

        // Dynamically add the rest of the *.aspx files in this directory as tests
        foreach (string path in Directory.GetFiles(Server.MapPath("~"), "*.aspx"))
        {
            string file = Path.GetFileName(path);
            if (string.Compare(file, "Default.aspx", StringComparison.OrdinalIgnoreCase) != 0 &&
                string.Compare(file, "TestHarnessTests.aspx", StringComparison.OrdinalIgnoreCase) != 0)
            {
                testSuites.Add(string.Format("'{0}'", file));
            }
        }

        // Pass the test suite URLs back to the client
        litTestSuiteUrls.Text = string.Join(" , ", testSuites.ToArray());

        // Look for a querystring flag to automatically run all the tests at once
        bool runAll = false;
        bool.TryParse(Request.QueryString["RunAll"], out runAll);
        litRunAllFlag.Text = runAll.ToString().ToLower();

        // Look for a querystring flag to run the tests in "debug mode"
        bool debug = false;
        bool.TryParse(Request.QueryString["Debug"], out debug);
        litDebugFlag.Text = debug.ToString().ToLower();
    }
}