//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Cui.Controls.PatientBannerControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PatientBannerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatientBannerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Cui.Controls.PatientBannerControl.PatientBannerResources", typeof(PatientBannerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string AddressItemSeparator {
            get {
                return ResourceManager.GetString("AddressItemSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usual address.
        /// </summary>
        internal static string AddressTypeLabelText {
            get {
                return ResourceManager.GetString("AddressTypeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age at death.
        /// </summary>
        internal static string AgeAtDeathLabelText {
            get {
                return ResourceManager.GetString("AgeAtDeathLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age at which the patient died.
        /// </summary>
        internal static string AgeAtDeathLabelTooltip {
            get {
                return ResourceManager.GetString("AgeAtDeathLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to open this section of the record.
        /// </summary>
        internal static string AgeAtDeathTooltip {
            get {
                return ResourceManager.GetString("AgeAtDeathTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Known.
        /// </summary>
        internal static string AgeNotKnown {
            get {
                return ResourceManager.GetString("AgeNotKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Microsoft.Cui.Controls;component/PatientBannerControl/AllergiesNotPresentIcon.png.
        /// </summary>
        internal static string AllergiesNotPresentIconURI {
            get {
                return ResourceManager.GetString("AllergiesNotPresentIconURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Microsoft.Cui.WPFControls;component/PatientBannerControl/AllergiesNotPresentIcon.png.
        /// </summary>
        internal static string AllergiesNotPresentIconWPFURI {
            get {
                return ResourceManager.GetString("AllergiesNotPresentIconWPFURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Microsoft.Cui.Controls;component/PatientBannerControl/AllergiesPresentIcon.png.
        /// </summary>
        internal static string AllergiesPresentIconURI {
            get {
                return ResourceManager.GetString("AllergiesPresentIconURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Microsoft.Cui.WPFControls;component/PatientBannerControl/AllergiesPresentIcon.png.
        /// </summary>
        internal static string AllergiesPresentIconWPFURI {
            get {
                return ResourceManager.GetString("AllergiesPresentIconWPFURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Microsoft.Cui.Controls;component/PatientBannerControl/AllergiesUnavailable.png.
        /// </summary>
        internal static string AllergiesUnavailableIconURI {
            get {
                return ResourceManager.GetString("AllergiesUnavailableIconURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Microsoft.Cui.WPFControls;component/PatientBannerControl/AllergiesUnavailable.png.
        /// </summary>
        internal static string AllergiesUnavailableIconWPFURI {
            get {
                return ResourceManager.GetString("AllergiesUnavailableIconWPFURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No known allergies.
        /// </summary>
        internal static string AllergyNotKnown {
            get {
                return ResourceManager.GetString("AllergyNotKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies not recorded.
        /// </summary>
        internal static string AllergyNotRecorded {
            get {
                return ResourceManager.GetString("AllergyNotRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known allergies.
        /// </summary>
        internal static string AllergyPresent {
            get {
                return ResourceManager.GetString("AllergyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies unavailable.
        /// </summary>
        internal static string AllergyUnavailable {
            get {
                return ResourceManager.GetString("AllergyUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Microsoft.Cui.Controls;component/PatientBannerControl/Collapse.png.
        /// </summary>
        internal static string CollapseImageURI {
            get {
                return ResourceManager.GetString("CollapseImageURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Microsoft.Cui.WPFControls;component/PatientBannerControl/Collapse.png.
        /// </summary>
        internal static string CollapseImageWPFURI {
            get {
                return ResourceManager.GetString("CollapseImageWPFURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Known.
        /// </summary>
        internal static string DateNotKnown {
            get {
                return ResourceManager.GetString("DateNotKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born.
        /// </summary>
        internal static string DateOfBirthLabelText {
            get {
                return ResourceManager.GetString("DateOfBirthLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string DateOfBirthLabelTooltip {
            get {
                return ResourceManager.GetString("DateOfBirthLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to open this section of the record.
        /// </summary>
        internal static string DateOfBirthTooltip {
            get {
                return ResourceManager.GetString("DateOfBirthTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Died.
        /// </summary>
        internal static string DateOfDeathLabelText {
            get {
                return ResourceManager.GetString("DateOfDeathLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Death.
        /// </summary>
        internal static string DateOfDeathLabelToolTip {
            get {
                return ResourceManager.GetString("DateOfDeathLabelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to open this section of the record.
        /// </summary>
        internal static string DateOfDeathToolTip {
            get {
                return ResourceManager.GetString("DateOfDeathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XXX XXX XXXX.
        /// </summary>
        internal static string DefaultIdentifierValue {
            get {
                return ResourceManager.GetString("DefaultIdentifierValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Microsoft.Cui.Controls;component/PatientBannerControl/Expand.png.
        /// </summary>
        internal static string DropDownImageURI {
            get {
                return ResourceManager.GetString("DropDownImageURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Microsoft.Cui.WPFControls;component/PatientBannerControl/Expand.png.
        /// </summary>
        internal static string DropDownImageWPFURI {
            get {
                return ResourceManager.GetString("DropDownImageWPFURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailLabelText {
            get {
                return ResourceManager.GetString("EmailLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FamilyName.
        /// </summary>
        internal static string FamilyName {
            get {
                return ResourceManager.GetString("FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth cannot be in future.
        /// </summary>
        internal static string FutureDateOfBirth {
            get {
                return ResourceManager.GetString("FutureDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of death cannot be in future.
        /// </summary>
        internal static string FutureDateOfDeath {
            get {
                return ResourceManager.GetString("FutureDateOfDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string GenderLabelText {
            get {
                return ResourceManager.GetString("GenderLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person&apos;s current Gender. This may differ from a person&apos;s Sex (which is the Gender registered at birth).
        /// </summary>
        internal static string GenderLabelTooltip {
            get {
                return ResourceManager.GetString("GenderLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to open this section of the record.
        /// </summary>
        internal static string GenderTooltip {
            get {
                return ResourceManager.GetString("GenderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GivenName.
        /// </summary>
        internal static string GivenName {
            get {
                return ResourceManager.GetString("GivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomePhoneLabelText {
            get {
                return ResourceManager.GetString("HomePhoneLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS No..
        /// </summary>
        internal static string IdentifierLabelText {
            get {
                return ResourceManager.GetString("IdentifierLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ten-digit number used to identify a person uniquely within the NHS in England and Wales.
        /// </summary>
        internal static string IdentifierLabelTooltip {
            get {
                return ResourceManager.GetString("IdentifierLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to open this section of the record.
        /// </summary>
        internal static string IdentifierTooltip {
            get {
                return ResourceManager.GetString("IdentifierTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify valid image path for the collapsed image.
        /// </summary>
        internal static string InvalidCollapsedImageValue {
            get {
                return ResourceManager.GetString("InvalidCollapsedImageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify valid image path for the drop down image.
        /// </summary>
        internal static string InvalidDropdownImageValue {
            get {
                return ResourceManager.GetString("InvalidDropdownImageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string MobilePhoneLabelText {
            get {
                return ResourceManager.GetString("MobilePhoneLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Microsoft.Cui.Controls;component/PatientBannerControl/Patient.png.
        /// </summary>
        internal static string PatientImageURI {
            get {
                return ResourceManager.GetString("PatientImageURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Microsoft.Cui.WPFControls;component/PatientBannerControl/Patient.png.
        /// </summary>
        internal static string PatientImageWPFURI {
            get {
                return ResourceManager.GetString("PatientImageWPFURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to open this section of the record.
        /// </summary>
        internal static string PatientNameToolTip {
            get {
                return ResourceManager.GetString("PatientNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred name.
        /// </summary>
        internal static string PreferredNameLabelText {
            get {
                return ResourceManager.GetString("PreferredNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name by which the patient prefers to be known.
        /// </summary>
        internal static string PreferredNameLabelToolTip {
            get {
                return ResourceManager.GetString("PreferredNameLabelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to open this section of the record.
        /// </summary>
        internal static string PreferredNameToolTip {
            get {
                return ResourceManager.GetString("PreferredNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string SubSectionOneTitle {
            get {
                return ResourceManager.GetString("SubSectionOneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone and email.
        /// </summary>
        internal static string SubSectionTwoTitle {
            get {
                return ResourceManager.GetString("SubSectionTwoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all addresses.
        /// </summary>
        internal static string ViewAllAddressesLinkText {
            get {
                return ResourceManager.GetString("ViewAllAddressesLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all contact details.
        /// </summary>
        internal static string ViewAllContactDetailsLinkText {
            get {
                return ResourceManager.GetString("ViewAllContactDetailsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View allergy record.
        /// </summary>
        internal static string ViewAllergyRecordLinkText {
            get {
                return ResourceManager.GetString("ViewAllergyRecordLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        internal static string WorkPhoneLabelText {
            get {
                return ResourceManager.GetString("WorkPhoneLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to expand or collapse.
        /// </summary>
        internal static string ZoneTwoTooltip {
            get {
                return ResourceManager.GetString("ZoneTwoTooltip", resourceCulture);
            }
        }
    }
}
