//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhsCui.Toolkit.Web.PatientBannerControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NhsCui.Toolkit.Web.PatientBannerControl.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age at death.
        /// </summary>
        internal static string AgeAtDeathLabelText {
            get {
                return ResourceManager.GetString("AgeAtDeathLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ({0}).
        /// </summary>
        internal static string AgeFormat {
            get {
                return ResourceManager.GetString("AgeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies unavailable.
        /// </summary>
        internal static string AllergiesUnavailable {
            get {
                return ResourceManager.GetString("AllergiesUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born.
        /// </summary>
        internal static string DateOfBirthLabelText {
            get {
                return ResourceManager.GetString("DateOfBirthLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Died.
        /// </summary>
        internal static string DateOfDeathLabelText {
            get {
                return ResourceManager.GetString("DateOfDeathLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailLabelText {
            get {
                return ResourceManager.GetString("EmailLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FamilyName.
        /// </summary>
        internal static string FamilyName {
            get {
                return ResourceManager.GetString("FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string GenderLabelText {
            get {
                return ResourceManager.GetString("GenderLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender: a person&apos;s current Gender. This may be different from a person&apos;s Sex which is a person&apos;s Gender defined at the point of birth registration..
        /// </summary>
        internal static string GenderLabelTooltip {
            get {
                return ResourceManager.GetString("GenderLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to open this section of the record.
        /// </summary>
        internal static string GenderValueTooltip {
            get {
                return ResourceManager.GetString("GenderValueTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GivenName.
        /// </summary>
        internal static string GivenName {
            get {
                return ResourceManager.GetString("GivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomePhoneLabelText {
            get {
                return ResourceManager.GetString("HomePhoneLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS No..
        /// </summary>
        internal static string IdentifierLabelText {
            get {
                return ResourceManager.GetString("IdentifierLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ten-digit number used to identify a person uniquely within the NHS in England and Wales.
        /// </summary>
        internal static string IdentifierLabelTooltip {
            get {
                return ResourceManager.GetString("IdentifierLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to open this section of the record.
        /// </summary>
        internal static string IdentifierTooltip {
            get {
                return ResourceManager.GetString("IdentifierTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NormalImage: &apos;{0}&apos;, ActiveImage: &apos;{1}&apos;, AlternativeText: &apos;{2}&apos;.
        /// </summary>
        internal static string ImageInfoToStringFormat {
            get {
                return ResourceManager.GetString("ImageInfoToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth cannot be in the future..
        /// </summary>
        internal static string InvalidDateOfBirthExcpetionMessage {
            get {
                return ResourceManager.GetString("InvalidDateOfBirthExcpetionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Death cannot be in the future..
        /// </summary>
        internal static string InvalidDateOfDeathExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidDateOfDeathExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string MobilePhoneLabelText {
            get {
                return ResourceManager.GetString("MobilePhoneLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More allergies present.
        /// </summary>
        internal static string MoreAllergiesLabel {
            get {
                return ResourceManager.GetString("MoreAllergiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;.
        /// </summary>
        internal static string NonBreakingSpace {
            get {
                return ResourceManager.GetString("NonBreakingSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No known allergies.
        /// </summary>
        internal static string NoneKnown {
            get {
                return ResourceManager.GetString("NoneKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies not recorded.
        /// </summary>
        internal static string NotRecorded {
            get {
                return ResourceManager.GetString("NotRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image of {0}.
        /// </summary>
        internal static string PatientImageAltTextFormat {
            get {
                return ResourceManager.GetString("PatientImageAltTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred name.
        /// </summary>
        internal static string PreferredNameLabelText {
            get {
                return ResourceManager.GetString("PreferredNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known allergies.
        /// </summary>
        internal static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;BR /&gt;.
        /// </summary>
        internal static string SeparatorControlHtmlText {
            get {
                return ResourceManager.GetString("SeparatorControlHtmlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SubsectionFiveTitle {
            get {
                return ResourceManager.GetString("SubsectionFiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SubsectionFourTitle {
            get {
                return ResourceManager.GetString("SubsectionFourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string SubsectionOneTitle {
            get {
                return ResourceManager.GetString("SubsectionOneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SubsectionThreeTitle {
            get {
                return ResourceManager.GetString("SubsectionThreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone and email.
        /// </summary>
        internal static string SubsectionTwoTitle {
            get {
                return ResourceManager.GetString("SubsectionTwoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control of id &apos;{0}&apos; could not be found in the Patient Banner control of id &apos;{1}&apos;.
        /// </summary>
        internal static string TemplateControlNotFoundMessage {
            get {
                return ResourceManager.GetString("TemplateControlNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Known.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all addresses.
        /// </summary>
        internal static string ViewAllAddressLinkText {
            get {
                return ResourceManager.GetString("ViewAllAddressLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all contact details.
        /// </summary>
        internal static string ViewAllContactDetailsLinkText {
            get {
                return ResourceManager.GetString("ViewAllContactDetailsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View allergy record.
        /// </summary>
        internal static string ViewAllergyRecordLinkText {
            get {
                return ResourceManager.GetString("ViewAllergyRecordLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        internal static string WorkPhoneLabelText {
            get {
                return ResourceManager.GetString("WorkPhoneLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to expand or collapse.
        /// </summary>
        internal static string ZoneTwoToolTipText {
            get {
                return ResourceManager.GetString("ZoneTwoToolTipText", resourceCulture);
            }
        }
    }
}
