//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Cui.SampleWinform.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Cui.SampleWinform.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon Computer {
            get {
                object obj = ResourceManager.GetObject("Computer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cuibann {
            get {
                object obj = ResourceManager.GetObject("cuibann", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap footer_1px {
            get {
                object obj = ResourceManager.GetObject("footer_1px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Introduction&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;WinUserControls.css&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    
        ///    &lt;div id=&quot;default_content&quot;&gt;
        ///        &lt;div class=&quot;heading&quot;&gt;
        ///            &lt;b&gt;Introduction&lt;/b&gt;
        ///        &lt;/div&gt;
        ///        &lt;p&gt;
        ///            Welcome to the NHS CUI Control Toolkit Sample Application. 
        ///            &lt;br /&gt;
        ///            This Application:
        ///            &lt;ul&gt;
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsCui.
        /// </summary>
        internal static string MsCui {
            get {
                return ResourceManager.GetString("MsCui", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap nhs_footer_img {
            get {
                object obj = ResourceManager.GetObject("nhs_footer_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nhs_headertop_img1 {
            get {
                object obj = ResourceManager.GetObject("nhs_headertop_img1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body, div, p, h1, h2, h3, h4, ul, li, table
        ///{
        ///	margin: 0;
        ///	padding: 0;
        ///	border: none;
        ///}
        ///
        ///body
        ///{
        ///	background: #B4B4B4;
        ///	font-family: Verdana, Tahoma, Arial, Sans-Serif;
        ///	font-size: 75%;
        ///}
        ///
        ///#default_header
        ///{
        ///	margin-top: 4px;
        ///	margin-bottom: 0px;
        ///	margin-left: auto;
        ///	margin-right: auto;
        ///	width: 1024px;
        ///}
        ///
        ///#default_headertop
        ///{
        ///	background: #3b71b6;
        ///	margin: 0px;
        ///}
        ///
        ///#default_page
        ///{
        ///	margin: 20px auto 20px auto;
        ///	width: 1024px;
        ///}
        ///
        ///#default_content
        ///{
        ///	width: 100%;
        ///	height: 10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WinUserControls {
            get {
                return ResourceManager.GetString("WinUserControls", resourceCulture);
            }
        }
    }
}
