//-----------------------------------------------------------------------
// <auto-generated>
// <copyright file="NameLabel.Designer.cs" company="Microsoft Corporation and Crown copyright 2007 - 2010.">
// Copyright (c) Microsoft Corporation and Crown copyright 2007 - 2010.
// All rights reserved.
//
// CERTAIN PARTS OF THIS WORK CONTAIN SOFTWARE CODE THAT IS LICENSED 
// FOR USE UNDER THE MICROSOFT PUBLIC LICENSE. DISTRIBUTION, IN SOURCE CODE 
// OR OBJECT CODE FORM, OF THOSE PARTS MUST COMPLY WITH THE TERMS OF THE 
// PUBLIC LICENSE. SEE http://www.microsoft.com/opensource/licenses.mspx 
// FOR DETAILS.  
// IF YOU BRING A PATENT CLAIM AGAINST ANY CONTRIBUTOR OVER PATENTS THAT 
// YOU CLAIM ARE INFRINGED BY THE PUBLIC LICENSE SOFTWARE, YOUR PATENT 
// LICENSE FROM SUCH CONTRIBUTOR TO THE SOFTWARE ENDS AUTOMATICALLY.
//
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
// </copyright>
// <summary>NameLabel Designer</summary>
// </auto-generated>
//-----------------------------------------------------------------------

namespace NhsCui.Toolkit.WinForms
{
    /// <summary>
    /// 
    /// </summary>
    public partial class NameLabel
    {
        /// <summary>
        /// nameFlowLayoutPanel memvar
        /// </summary>
        private System.Windows.Forms.FlowLayoutPanel nameFlowLayoutPanel;

        /// <summary>
        /// LastNameLabel memvar
        /// </summary>
        private System.Windows.Forms.Label familyNameLabel;

        /// <summary>
        /// givenNameLabel memvar
        /// </summary>
        private System.Windows.Forms.Label givenNameLabel;

        /// <summary>
        /// titleLabel memvar
        /// </summary>
        private System.Windows.Forms.Label titleLabel;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.nameFlowLayoutPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.familyNameLabel = new System.Windows.Forms.Label();
            this.givenNameLabel = new System.Windows.Forms.Label();
            this.titleLabel = new System.Windows.Forms.Label();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.nameFlowLayoutPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // nameFlowLayoutPanel
            // 
            this.nameFlowLayoutPanel.Controls.Add(this.familyNameLabel);
            this.nameFlowLayoutPanel.Controls.Add(this.givenNameLabel);
            this.nameFlowLayoutPanel.Controls.Add(this.titleLabel);
            this.nameFlowLayoutPanel.Location = new System.Drawing.Point(0, 0);
            this.nameFlowLayoutPanel.Name = "nameFlowLayoutPanel";
            this.nameFlowLayoutPanel.Size = new System.Drawing.Size(150, 13);
            this.nameFlowLayoutPanel.TabIndex = 0;
            // 
            // familyNameLabel
            // 
            this.familyNameLabel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)));
            this.familyNameLabel.AutoSize = true;
            this.familyNameLabel.Location = new System.Drawing.Point(0, 0);
            this.familyNameLabel.Margin = new System.Windows.Forms.Padding(0);
            this.familyNameLabel.Name = "familyNameLabel";
            this.familyNameLabel.Size = new System.Drawing.Size(79, 13);
            this.familyNameLabel.TabIndex = 0;
            this.familyNameLabel.Text = NameLabelControl.Resources.FamilyNameDefaultDesignTimeValue;
            this.familyNameLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // givenNameLabel
            // 
            this.givenNameLabel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)));
            this.givenNameLabel.AutoSize = true;
            this.givenNameLabel.Location = new System.Drawing.Point(79, 0);
            this.givenNameLabel.Margin = new System.Windows.Forms.Padding(0);
            this.givenNameLabel.Name = "givenNameLabel";
            this.givenNameLabel.Size = new System.Drawing.Size(64, 13);
            this.givenNameLabel.TabIndex = 1;
            this.givenNameLabel.Text = NameLabelControl.Resources.GivenNameDefaultDesignTimeValue;
            this.givenNameLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // titleLabel
            // 
            this.titleLabel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)));
            this.titleLabel.AutoSize = true;
            this.titleLabel.Location = new System.Drawing.Point(0, 13);
            this.titleLabel.Margin = new System.Windows.Forms.Padding(0);
            this.titleLabel.Name = "titleLabel";
            this.titleLabel.Size = new System.Drawing.Size(27, 13);
            this.titleLabel.TabIndex = 2;
            this.titleLabel.Text = NameLabelControl.Resources.TitelDefaultDesignTimeValue;
            this.titleLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // NameLabel
            // 
            this.Controls.Add(this.nameFlowLayoutPanel);
            this.Name = "NameLabel";
            this.Size = new System.Drawing.Size(150, 16);
            this.Resize += new System.EventHandler(this.NameLabel_Resize);
            this.nameFlowLayoutPanel.ResumeLayout(false);
            this.nameFlowLayoutPanel.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.ToolTip toolTip1;
    }
}
