//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhsCui.Toolkit.WinForms.TimeInputBoxControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NhsCui.Toolkit.WinForms.TimeInputBoxControl.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi Enter a time (e.g. \b &apos;1624&apos;\b0. or  \b &apos;16:24&apos; \b0) or type a time period (e.g. \b&apos;afternoon&apos;\b0, \b&apos;evening&apos;\b0). Alternatively use the \b arrow keys \b0 or \b spinner \b0 to change the hours and minutes.}.
        /// </summary>
        internal static string FirstUseToolTip {
            get {
                return ResourceManager.GetString("FirstUseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a time (e.g. &apos;1624&apos; or 16:24) or type a time period (e.g. &apos;afternoon&apos;, &apos;evening&apos;). Alternatively use the arrow keys or spinner to change the hours and minutes..
        /// </summary>
        internal static string FirstUseToolTipSimple {
            get {
                return ResourceManager.GetString("FirstUseToolTipSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrement Time.
        /// </summary>
        internal static string SpinDownButtonTitle {
            get {
                return ResourceManager.GetString("SpinDownButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Time.
        /// </summary>
        internal static string SpinUpButtonTitle {
            get {
                return ResourceManager.GetString("SpinUpButtonTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nhs time input box.
        /// </summary>
        internal static string AccessibleName
        {
            get
            {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Control used to accept the time from the user.
        /// </summary>
        internal static string AccessibleDescription
        {
            get
            {
                return ResourceManager.GetString("AccessibleDescription", resourceCulture);
            }
        }
    }
}
